WARNING 2020-12-01 15:54:05,442 [pipeline_server.py:479] [CONF] build_dag_each_worker not set, use default: False
WARNING 2020-12-01 15:54:05,443 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 15:54:05,443 [pipeline_server.py:479] [CONF] channel_size not set, use default: 0
WARNING 2020-12-01 15:54:05,443 [pipeline_server.py:479] [CONF] use_profile not set, use default: False
WARNING 2020-12-01 15:54:05,443 [pipeline_server.py:479] [CONF] client_type not set, use default: brpc
WARNING 2020-12-01 15:54:05,443 [pipeline_server.py:479] [CONF] tracer not set, use default: {}
WARNING 2020-12-01 15:54:05,443 [pipeline_server.py:479] [CONF] interval_s not set, use default: -1
WARNING 2020-12-01 15:54:05,443 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 15:54:05,443 [pipeline_server.py:479] [CONF] concurrency not set, use default: 1
WARNING 2020-12-01 15:54:05,443 [pipeline_server.py:479] [CONF] batch_size not set, use default: 1
WARNING 2020-12-01 15:54:05,443 [pipeline_server.py:479] [CONF] timeout not set, use default: -1
WARNING 2020-12-01 15:54:05,443 [pipeline_server.py:479] [CONF] auto_batching_timeout not set, use default: -1
WARNING 2020-12-01 15:54:05,443 [pipeline_server.py:479] [CONF] ir_optim not set, use default: False
WARNING 2020-12-01 15:54:05,444 [pipeline_server.py:479] [CONF] mem_optim not set, use default: True
WARNING 2020-12-01 15:54:05,444 [pipeline_server.py:479] [CONF] workdir not set, use default: 
WARNING 2020-12-01 15:54:05,444 [pipeline_server.py:479] [CONF] thread_num not set, use default: 2
WARNING 2020-12-01 15:54:05,444 [operator.py:128] imagenet Because auto_batching_timeout <= 0 or batch_size == 1, set auto_batching_timeout to None.
INFO 2020-12-01 15:54:05,444 [operator.py:151] local_service_conf: {'mem_optim': True, 'workdir': '', 'model_config': 'ResNet50_vd_model', 'devices': '0', 'fetch_list': ['price'], 'client_type': 'local_predictor', 'thread_num': 2, 'concurrency': 2, 'ir_optim': False}
INFO 2020-12-01 15:54:05,444 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12001])
INFO 2020-12-01 15:54:05,444 [operator.py:229] imagenet 
	input_ops: @DAGExecutor,
	server_endpoints: None
	fetch_list: ['price']
	client_config: ResNet50_vd_model/serving_server_conf.prototxt
	concurrency: 1,
	timeout(s): -1,
	retry: 1,
	batch_size: 1,
	auto_batching_timeout(s): None
INFO 2020-12-01 15:54:05,445 [pipeline_server.py:204] ============= PIPELINE SERVER =============
INFO 2020-12-01 15:54:05,445 [pipeline_server.py:207] 
{
    "worker_num":1,
    "dag":{
        "retry":1,
        "channel_size":0,
        "use_profile":false,
        "is_thread_op":false,
        "client_type":"brpc",
        "tracer":{
            "interval_s":-1
        }
    },
    "build_dag_each_worker":false,
    "http_port":18082,
    "op":{
        "imagenet":{
            "local_service_conf":{
                "mem_optim":true,
                "workdir":"",
                "model_config":"ResNet50_vd_model",
                "devices":"0",
                "fetch_list":[
                    "price"
                ],
                "client_type":"local_predictor",
                "thread_num":2,
                "concurrency":2,
                "ir_optim":false
            },
            "retry":1,
            "concurrency":1,
            "batch_size":1,
            "timeout":-1,
            "auto_batching_timeout":-1
        }
    }
}
INFO 2020-12-01 15:54:05,445 [pipeline_server.py:212] -------------------------------------------
INFO 2020-12-01 15:54:05,445 [operator.py:252] Op(imagenet) use local rpc service at port: [12001]
INFO 2020-12-01 15:54:05,464 [dag.py:493] [DAG] Succ init
INFO 2020-12-01 15:54:05,465 [dag.py:651] ================= USED OP =================
INFO 2020-12-01 15:54:05,465 [dag.py:654] imagenet
INFO 2020-12-01 15:54:05,465 [dag.py:655] -------------------------------------------
INFO 2020-12-01 15:54:05,500 [dag.py:784] [DAG] Succ build DAG
INFO 2020-12-01 15:54:05,504 [dag.py:816] [DAG] start
INFO 2020-12-01 15:54:05,505 [dag.py:181] [DAG] set in channel succ, name [@DAGExecutor]
INFO 2020-12-01 15:54:05,508 [pipeline_server.py:46] [PipelineServicer] succ init
INFO 2020-12-01 15:54:05,518 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12002])
INFO 2020-12-01 15:54:05,518 [operator.py:1036] Init cuda env in process 0
INFO 2020-12-01 15:54:06,395 [local_predict.py:85] load_model_config params: model_path:ResNet50_vd_model, use_gpu:True,            gpu_id:0, use_profile:False, thread_num:2, mem_optim:True, ir_optim:False,            use_trt:False, use_feed_fetch_ops:False
INFO 2020-12-01 15:54:07,958 [operator.py:1046] [imagenet|0] Succ init
WARNING 2020-12-01 15:58:15,579 [pipeline_server.py:479] [CONF] build_dag_each_worker not set, use default: False
WARNING 2020-12-01 15:58:15,580 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 15:58:15,580 [pipeline_server.py:479] [CONF] channel_size not set, use default: 0
WARNING 2020-12-01 15:58:15,580 [pipeline_server.py:479] [CONF] use_profile not set, use default: False
WARNING 2020-12-01 15:58:15,580 [pipeline_server.py:479] [CONF] client_type not set, use default: brpc
WARNING 2020-12-01 15:58:15,580 [pipeline_server.py:479] [CONF] tracer not set, use default: {}
WARNING 2020-12-01 15:58:15,580 [pipeline_server.py:479] [CONF] interval_s not set, use default: -1
WARNING 2020-12-01 15:58:15,580 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 15:58:15,580 [pipeline_server.py:479] [CONF] concurrency not set, use default: 1
WARNING 2020-12-01 15:58:15,580 [pipeline_server.py:479] [CONF] batch_size not set, use default: 1
WARNING 2020-12-01 15:58:15,581 [pipeline_server.py:479] [CONF] timeout not set, use default: -1
WARNING 2020-12-01 15:58:15,581 [pipeline_server.py:479] [CONF] auto_batching_timeout not set, use default: -1
WARNING 2020-12-01 15:58:15,581 [pipeline_server.py:479] [CONF] ir_optim not set, use default: False
WARNING 2020-12-01 15:58:15,581 [pipeline_server.py:479] [CONF] mem_optim not set, use default: True
WARNING 2020-12-01 15:58:15,581 [pipeline_server.py:479] [CONF] workdir not set, use default: 
WARNING 2020-12-01 15:58:15,581 [pipeline_server.py:479] [CONF] thread_num not set, use default: 2
WARNING 2020-12-01 15:58:15,581 [operator.py:128] imagenet Because auto_batching_timeout <= 0 or batch_size == 1, set auto_batching_timeout to None.
INFO 2020-12-01 15:58:15,581 [operator.py:151] local_service_conf: {'mem_optim': True, 'workdir': '', 'model_config': 'ResNet50_vd_model', 'devices': '0', 'fetch_list': ['price'], 'client_type': 'local_predictor', 'thread_num': 2, 'concurrency': 2, 'ir_optim': False}
INFO 2020-12-01 15:58:15,582 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12000])
INFO 2020-12-01 15:58:15,582 [operator.py:229] imagenet 
	input_ops: @DAGExecutor,
	server_endpoints: None
	fetch_list: ['price']
	client_config: ResNet50_vd_model/serving_server_conf.prototxt
	concurrency: 1,
	timeout(s): -1,
	retry: 1,
	batch_size: 1,
	auto_batching_timeout(s): None
INFO 2020-12-01 15:58:15,582 [pipeline_server.py:204] ============= PIPELINE SERVER =============
INFO 2020-12-01 15:58:15,582 [pipeline_server.py:207] 
{
    "dag":{
        "retry":1,
        "channel_size":0,
        "use_profile":false,
        "is_thread_op":false,
        "client_type":"brpc",
        "tracer":{
            "interval_s":-1
        }
    },
    "rpc_port":9999,
    "worker_num":1,
    "http_port":18082,
    "build_dag_each_worker":false,
    "op":{
        "imagenet":{
            "local_service_conf":{
                "mem_optim":true,
                "workdir":"",
                "model_config":"ResNet50_vd_model",
                "devices":"0",
                "fetch_list":[
                    "price"
                ],
                "client_type":"local_predictor",
                "thread_num":2,
                "concurrency":2,
                "ir_optim":false
            },
            "retry":1,
            "concurrency":1,
            "batch_size":1,
            "timeout":-1,
            "auto_batching_timeout":-1
        }
    }
}
INFO 2020-12-01 15:58:15,582 [pipeline_server.py:212] -------------------------------------------
INFO 2020-12-01 15:58:15,582 [operator.py:252] Op(imagenet) use local rpc service at port: [12000]
INFO 2020-12-01 15:58:15,597 [dag.py:493] [DAG] Succ init
INFO 2020-12-01 15:58:15,598 [dag.py:651] ================= USED OP =================
INFO 2020-12-01 15:58:15,599 [dag.py:654] imagenet
INFO 2020-12-01 15:58:15,599 [dag.py:655] -------------------------------------------
INFO 2020-12-01 15:58:15,633 [dag.py:784] [DAG] Succ build DAG
INFO 2020-12-01 15:58:15,638 [dag.py:816] [DAG] start
INFO 2020-12-01 15:58:15,639 [dag.py:181] [DAG] set in channel succ, name [@DAGExecutor]
INFO 2020-12-01 15:58:15,642 [pipeline_server.py:46] [PipelineServicer] succ init
INFO 2020-12-01 15:58:15,652 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12001])
INFO 2020-12-01 15:58:15,652 [operator.py:1036] Init cuda env in process 0
INFO 2020-12-01 15:58:16,467 [local_predict.py:85] load_model_config params: model_path:ResNet50_vd_model, use_gpu:True,            gpu_id:0, use_profile:False, thread_num:2, mem_optim:True, ir_optim:False,            use_trt:False, use_feed_fetch_ops:False
INFO 2020-12-01 15:58:18,006 [operator.py:1046] [imagenet|0] Succ init
INFO 2020-12-01 15:58:30,870 [pipeline_server.py:50] (log_id=0) inference request name: self.name:imagenet
INFO 2020-12-01 15:58:30,872 [operator.py:1285] RequestOp unpack one request. log_id:0, clientip:172.17.0.8             name:, method:
INFO 2020-12-01 15:58:30,872 [dag.py:368] (data_id=0 log_id=0) Succ Generate ID 
ERROR 2020-12-01 15:58:30,878 [operator.py:639] (data_id=0 log_id=0) [imagenet|0] Failed to preprocess: global name 'base64' is not defined
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/paddle_serving_server_gpu/pipeline/operator.py", line 622, in _run_preprocess
    parsed_data, data_id, logid_dict.get(data_id))
  File "resnet50_web_service.py", line 40, in preprocess
    data = base64.b64decode(input_dict["image"].encode('utf8'))
NameError: global name 'base64' is not defined
ERROR 2020-12-01 15:58:30,881 [dag.py:409] (data_id=0 log_id=0) Failed to predict: (data_id=0 log_id=0) [imagenet|0] Failed to preprocess: global name 'base64' is not defined
WARNING 2020-12-01 15:59:32,755 [pipeline_server.py:479] [CONF] build_dag_each_worker not set, use default: False
WARNING 2020-12-01 15:59:32,756 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 15:59:32,756 [pipeline_server.py:479] [CONF] channel_size not set, use default: 0
WARNING 2020-12-01 15:59:32,756 [pipeline_server.py:479] [CONF] use_profile not set, use default: False
WARNING 2020-12-01 15:59:32,756 [pipeline_server.py:479] [CONF] client_type not set, use default: brpc
WARNING 2020-12-01 15:59:32,756 [pipeline_server.py:479] [CONF] tracer not set, use default: {}
WARNING 2020-12-01 15:59:32,756 [pipeline_server.py:479] [CONF] interval_s not set, use default: -1
WARNING 2020-12-01 15:59:32,756 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 15:59:32,756 [pipeline_server.py:479] [CONF] concurrency not set, use default: 1
WARNING 2020-12-01 15:59:32,757 [pipeline_server.py:479] [CONF] batch_size not set, use default: 1
WARNING 2020-12-01 15:59:32,757 [pipeline_server.py:479] [CONF] timeout not set, use default: -1
WARNING 2020-12-01 15:59:32,757 [pipeline_server.py:479] [CONF] auto_batching_timeout not set, use default: -1
WARNING 2020-12-01 15:59:32,757 [pipeline_server.py:479] [CONF] ir_optim not set, use default: False
WARNING 2020-12-01 15:59:32,757 [pipeline_server.py:479] [CONF] mem_optim not set, use default: True
WARNING 2020-12-01 15:59:32,757 [pipeline_server.py:479] [CONF] workdir not set, use default: 
WARNING 2020-12-01 15:59:32,757 [pipeline_server.py:479] [CONF] thread_num not set, use default: 2
WARNING 2020-12-01 15:59:32,757 [operator.py:128] imagenet Because auto_batching_timeout <= 0 or batch_size == 1, set auto_batching_timeout to None.
INFO 2020-12-01 15:59:32,758 [operator.py:151] local_service_conf: {'mem_optim': True, 'workdir': '', 'model_config': 'ResNet50_vd_model', 'devices': '0', 'fetch_list': ['price'], 'client_type': 'local_predictor', 'thread_num': 2, 'concurrency': 2, 'ir_optim': False}
INFO 2020-12-01 15:59:32,758 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12000])
INFO 2020-12-01 15:59:32,758 [operator.py:229] imagenet 
	input_ops: @DAGExecutor,
	server_endpoints: None
	fetch_list: ['price']
	client_config: ResNet50_vd_model/serving_server_conf.prototxt
	concurrency: 1,
	timeout(s): -1,
	retry: 1,
	batch_size: 1,
	auto_batching_timeout(s): None
INFO 2020-12-01 15:59:32,758 [pipeline_server.py:204] ============= PIPELINE SERVER =============
INFO 2020-12-01 15:59:32,758 [pipeline_server.py:207] 
{
    "dag":{
        "retry":1,
        "channel_size":0,
        "use_profile":false,
        "is_thread_op":false,
        "client_type":"brpc",
        "tracer":{
            "interval_s":-1
        }
    },
    "rpc_port":9999,
    "worker_num":1,
    "http_port":18082,
    "build_dag_each_worker":false,
    "op":{
        "imagenet":{
            "local_service_conf":{
                "mem_optim":true,
                "workdir":"",
                "model_config":"ResNet50_vd_model",
                "devices":"0",
                "fetch_list":[
                    "price"
                ],
                "client_type":"local_predictor",
                "thread_num":2,
                "concurrency":2,
                "ir_optim":false
            },
            "retry":1,
            "concurrency":1,
            "batch_size":1,
            "timeout":-1,
            "auto_batching_timeout":-1
        }
    }
}
INFO 2020-12-01 15:59:32,758 [pipeline_server.py:212] -------------------------------------------
INFO 2020-12-01 15:59:32,758 [operator.py:252] Op(imagenet) use local rpc service at port: [12000]
INFO 2020-12-01 15:59:32,774 [dag.py:493] [DAG] Succ init
INFO 2020-12-01 15:59:32,775 [dag.py:651] ================= USED OP =================
INFO 2020-12-01 15:59:32,775 [dag.py:654] imagenet
INFO 2020-12-01 15:59:32,775 [dag.py:655] -------------------------------------------
INFO 2020-12-01 15:59:32,818 [dag.py:784] [DAG] Succ build DAG
INFO 2020-12-01 15:59:32,823 [dag.py:816] [DAG] start
INFO 2020-12-01 15:59:32,824 [dag.py:181] [DAG] set in channel succ, name [@DAGExecutor]
INFO 2020-12-01 15:59:32,827 [pipeline_server.py:46] [PipelineServicer] succ init
INFO 2020-12-01 15:59:32,837 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12001])
INFO 2020-12-01 15:59:32,838 [operator.py:1036] Init cuda env in process 0
INFO 2020-12-01 15:59:33,646 [local_predict.py:85] load_model_config params: model_path:ResNet50_vd_model, use_gpu:True,            gpu_id:0, use_profile:False, thread_num:2, mem_optim:True, ir_optim:False,            use_trt:False, use_feed_fetch_ops:False
INFO 2020-12-01 15:59:35,179 [operator.py:1046] [imagenet|0] Succ init
INFO 2020-12-01 15:59:38,222 [pipeline_server.py:50] (log_id=0) inference request name: self.name:imagenet
INFO 2020-12-01 15:59:38,224 [operator.py:1285] RequestOp unpack one request. log_id:0, clientip:172.17.0.8             name:, method:
INFO 2020-12-01 15:59:38,225 [dag.py:368] (data_id=0 log_id=0) Succ Generate ID 
ERROR 2020-12-01 15:59:38,249 [operator.py:639] (data_id=0 log_id=0) [imagenet|0] Failed to preprocess: 'numpy.ndarray' object has no attribute 'strip'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/paddle_serving_server_gpu/pipeline/operator.py", line 622, in _run_preprocess
    parsed_data, data_id, logid_dict.get(data_id))
  File "resnet50_web_service.py", line 44, in preprocess
    img = self.seq(im)
  File "/usr/lib/python2.7/site-packages/paddle_serving_app/reader/image_reader.py", line 486, in __call__
    img = t(img)
  File "/usr/lib/python2.7/site-packages/paddle_serving_app/reader/image_reader.py", line 562, in __call__
    resp = urllib.urlopen(img_url)
  File "/usr/lib64/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib64/python2.7/urllib.py", line 180, in open
    fullurl = unwrap(toBytes(fullurl))
  File "/usr/lib64/python2.7/urllib.py", line 1059, in unwrap
    url = url.strip()
AttributeError: 'numpy.ndarray' object has no attribute 'strip'
ERROR 2020-12-01 15:59:38,253 [dag.py:409] (data_id=0 log_id=0) Failed to predict: (data_id=0 log_id=0) [imagenet|0] Failed to preprocess: 'numpy.ndarray' object has no attribute 'strip'
WARNING 2020-12-01 16:00:43,240 [pipeline_server.py:479] [CONF] build_dag_each_worker not set, use default: False
WARNING 2020-12-01 16:00:43,241 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 16:00:43,241 [pipeline_server.py:479] [CONF] channel_size not set, use default: 0
WARNING 2020-12-01 16:00:43,241 [pipeline_server.py:479] [CONF] use_profile not set, use default: False
WARNING 2020-12-01 16:00:43,241 [pipeline_server.py:479] [CONF] client_type not set, use default: brpc
WARNING 2020-12-01 16:00:43,241 [pipeline_server.py:479] [CONF] tracer not set, use default: {}
WARNING 2020-12-01 16:00:43,241 [pipeline_server.py:479] [CONF] interval_s not set, use default: -1
WARNING 2020-12-01 16:00:43,241 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 16:00:43,241 [pipeline_server.py:479] [CONF] concurrency not set, use default: 1
WARNING 2020-12-01 16:00:43,241 [pipeline_server.py:479] [CONF] batch_size not set, use default: 1
WARNING 2020-12-01 16:00:43,242 [pipeline_server.py:479] [CONF] timeout not set, use default: -1
WARNING 2020-12-01 16:00:43,242 [pipeline_server.py:479] [CONF] auto_batching_timeout not set, use default: -1
WARNING 2020-12-01 16:00:43,242 [pipeline_server.py:479] [CONF] ir_optim not set, use default: False
WARNING 2020-12-01 16:00:43,242 [pipeline_server.py:479] [CONF] mem_optim not set, use default: True
WARNING 2020-12-01 16:00:43,242 [pipeline_server.py:479] [CONF] workdir not set, use default: 
WARNING 2020-12-01 16:00:43,242 [pipeline_server.py:479] [CONF] thread_num not set, use default: 2
WARNING 2020-12-01 16:00:43,242 [operator.py:128] imagenet Because auto_batching_timeout <= 0 or batch_size == 1, set auto_batching_timeout to None.
INFO 2020-12-01 16:00:43,243 [operator.py:151] local_service_conf: {'mem_optim': True, 'workdir': '', 'model_config': 'ResNet50_vd_model', 'devices': '0', 'fetch_list': ['price'], 'client_type': 'local_predictor', 'thread_num': 2, 'concurrency': 2, 'ir_optim': False}
INFO 2020-12-01 16:00:43,243 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12000])
INFO 2020-12-01 16:00:43,243 [operator.py:229] imagenet 
	input_ops: @DAGExecutor,
	server_endpoints: None
	fetch_list: ['price']
	client_config: ResNet50_vd_model/serving_server_conf.prototxt
	concurrency: 1,
	timeout(s): -1,
	retry: 1,
	batch_size: 1,
	auto_batching_timeout(s): None
INFO 2020-12-01 16:00:43,243 [pipeline_server.py:204] ============= PIPELINE SERVER =============
INFO 2020-12-01 16:00:43,243 [pipeline_server.py:207] 
{
    "dag":{
        "retry":1,
        "channel_size":0,
        "use_profile":false,
        "is_thread_op":false,
        "client_type":"brpc",
        "tracer":{
            "interval_s":-1
        }
    },
    "rpc_port":9999,
    "worker_num":1,
    "http_port":18082,
    "build_dag_each_worker":false,
    "op":{
        "imagenet":{
            "local_service_conf":{
                "mem_optim":true,
                "workdir":"",
                "model_config":"ResNet50_vd_model",
                "devices":"0",
                "fetch_list":[
                    "price"
                ],
                "client_type":"local_predictor",
                "thread_num":2,
                "concurrency":2,
                "ir_optim":false
            },
            "retry":1,
            "concurrency":1,
            "batch_size":1,
            "timeout":-1,
            "auto_batching_timeout":-1
        }
    }
}
INFO 2020-12-01 16:00:43,243 [pipeline_server.py:212] -------------------------------------------
INFO 2020-12-01 16:00:43,243 [operator.py:252] Op(imagenet) use local rpc service at port: [12000]
INFO 2020-12-01 16:00:43,258 [dag.py:493] [DAG] Succ init
INFO 2020-12-01 16:00:43,259 [dag.py:651] ================= USED OP =================
INFO 2020-12-01 16:00:43,259 [dag.py:654] imagenet
INFO 2020-12-01 16:00:43,259 [dag.py:655] -------------------------------------------
INFO 2020-12-01 16:00:43,292 [dag.py:784] [DAG] Succ build DAG
INFO 2020-12-01 16:00:43,297 [dag.py:816] [DAG] start
INFO 2020-12-01 16:00:43,298 [dag.py:181] [DAG] set in channel succ, name [@DAGExecutor]
INFO 2020-12-01 16:00:43,300 [pipeline_server.py:46] [PipelineServicer] succ init
INFO 2020-12-01 16:00:43,310 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12001])
INFO 2020-12-01 16:00:43,310 [operator.py:1036] Init cuda env in process 0
INFO 2020-12-01 16:00:44,080 [local_predict.py:85] load_model_config params: model_path:ResNet50_vd_model, use_gpu:True,            gpu_id:0, use_profile:False, thread_num:2, mem_optim:True, ir_optim:False,            use_trt:False, use_feed_fetch_ops:False
INFO 2020-12-01 16:00:45,582 [operator.py:1046] [imagenet|0] Succ init
INFO 2020-12-01 16:00:47,461 [pipeline_server.py:50] (log_id=0) inference request name: self.name:imagenet
INFO 2020-12-01 16:00:47,462 [operator.py:1285] RequestOp unpack one request. log_id:0, clientip:172.17.0.8             name:, method:
INFO 2020-12-01 16:00:47,463 [dag.py:368] (data_id=0 log_id=0) Succ Generate ID 
ERROR 2020-12-01 16:00:47,475 [operator.py:639] (data_id=0 log_id=0) [imagenet|0] Failed to preprocess: 'numpy.ndarray' object has no attribute 'strip'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/paddle_serving_server_gpu/pipeline/operator.py", line 622, in _run_preprocess
    parsed_data, data_id, logid_dict.get(data_id))
  File "resnet50_web_service.py", line 45, in preprocess
    img = self.seq(im)
  File "/usr/lib/python2.7/site-packages/paddle_serving_app/reader/image_reader.py", line 486, in __call__
    img = t(img)
  File "/usr/lib/python2.7/site-packages/paddle_serving_app/reader/image_reader.py", line 562, in __call__
    resp = urllib.urlopen(img_url)
  File "/usr/lib64/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib64/python2.7/urllib.py", line 180, in open
    fullurl = unwrap(toBytes(fullurl))
  File "/usr/lib64/python2.7/urllib.py", line 1059, in unwrap
    url = url.strip()
AttributeError: 'numpy.ndarray' object has no attribute 'strip'
ERROR 2020-12-01 16:00:47,479 [dag.py:409] (data_id=0 log_id=0) Failed to predict: (data_id=0 log_id=0) [imagenet|0] Failed to preprocess: 'numpy.ndarray' object has no attribute 'strip'
WARNING 2020-12-01 16:02:33,547 [pipeline_server.py:479] [CONF] build_dag_each_worker not set, use default: False
WARNING 2020-12-01 16:02:33,547 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 16:02:33,547 [pipeline_server.py:479] [CONF] channel_size not set, use default: 0
WARNING 2020-12-01 16:02:33,547 [pipeline_server.py:479] [CONF] use_profile not set, use default: False
WARNING 2020-12-01 16:02:33,547 [pipeline_server.py:479] [CONF] client_type not set, use default: brpc
WARNING 2020-12-01 16:02:33,547 [pipeline_server.py:479] [CONF] tracer not set, use default: {}
WARNING 2020-12-01 16:02:33,547 [pipeline_server.py:479] [CONF] interval_s not set, use default: -1
WARNING 2020-12-01 16:02:33,547 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 16:02:33,548 [pipeline_server.py:479] [CONF] concurrency not set, use default: 1
WARNING 2020-12-01 16:02:33,548 [pipeline_server.py:479] [CONF] batch_size not set, use default: 1
WARNING 2020-12-01 16:02:33,548 [pipeline_server.py:479] [CONF] timeout not set, use default: -1
WARNING 2020-12-01 16:02:33,548 [pipeline_server.py:479] [CONF] auto_batching_timeout not set, use default: -1
WARNING 2020-12-01 16:02:33,548 [pipeline_server.py:479] [CONF] ir_optim not set, use default: False
WARNING 2020-12-01 16:02:33,548 [pipeline_server.py:479] [CONF] mem_optim not set, use default: True
WARNING 2020-12-01 16:02:33,548 [pipeline_server.py:479] [CONF] workdir not set, use default: 
WARNING 2020-12-01 16:02:33,548 [pipeline_server.py:479] [CONF] thread_num not set, use default: 2
WARNING 2020-12-01 16:02:33,549 [operator.py:128] imagenet Because auto_batching_timeout <= 0 or batch_size == 1, set auto_batching_timeout to None.
INFO 2020-12-01 16:02:33,549 [operator.py:151] local_service_conf: {'mem_optim': True, 'workdir': '', 'model_config': 'ResNet50_vd_model', 'devices': '0', 'fetch_list': ['price'], 'client_type': 'local_predictor', 'thread_num': 2, 'concurrency': 2, 'ir_optim': False}
INFO 2020-12-01 16:02:33,549 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12000])
INFO 2020-12-01 16:02:33,549 [operator.py:229] imagenet 
	input_ops: @DAGExecutor,
	server_endpoints: None
	fetch_list: ['price']
	client_config: ResNet50_vd_model/serving_server_conf.prototxt
	concurrency: 1,
	timeout(s): -1,
	retry: 1,
	batch_size: 1,
	auto_batching_timeout(s): None
INFO 2020-12-01 16:02:33,549 [pipeline_server.py:204] ============= PIPELINE SERVER =============
INFO 2020-12-01 16:02:33,549 [pipeline_server.py:207] 
{
    "dag":{
        "retry":1,
        "channel_size":0,
        "use_profile":false,
        "is_thread_op":false,
        "client_type":"brpc",
        "tracer":{
            "interval_s":-1
        }
    },
    "rpc_port":9999,
    "worker_num":1,
    "http_port":18082,
    "build_dag_each_worker":false,
    "op":{
        "imagenet":{
            "local_service_conf":{
                "mem_optim":true,
                "workdir":"",
                "model_config":"ResNet50_vd_model",
                "devices":"0",
                "fetch_list":[
                    "price"
                ],
                "client_type":"local_predictor",
                "thread_num":2,
                "concurrency":2,
                "ir_optim":false
            },
            "retry":1,
            "concurrency":1,
            "batch_size":1,
            "timeout":-1,
            "auto_batching_timeout":-1
        }
    }
}
INFO 2020-12-01 16:02:33,549 [pipeline_server.py:212] -------------------------------------------
INFO 2020-12-01 16:02:33,549 [operator.py:252] Op(imagenet) use local rpc service at port: [12000]
INFO 2020-12-01 16:02:33,564 [dag.py:493] [DAG] Succ init
INFO 2020-12-01 16:02:33,565 [dag.py:651] ================= USED OP =================
INFO 2020-12-01 16:02:33,565 [dag.py:654] imagenet
INFO 2020-12-01 16:02:33,565 [dag.py:655] -------------------------------------------
INFO 2020-12-01 16:02:33,599 [dag.py:784] [DAG] Succ build DAG
INFO 2020-12-01 16:02:33,604 [dag.py:816] [DAG] start
INFO 2020-12-01 16:02:33,605 [dag.py:181] [DAG] set in channel succ, name [@DAGExecutor]
INFO 2020-12-01 16:02:33,607 [pipeline_server.py:46] [PipelineServicer] succ init
INFO 2020-12-01 16:02:33,617 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12001])
INFO 2020-12-01 16:02:33,617 [operator.py:1036] Init cuda env in process 0
INFO 2020-12-01 16:02:34,403 [local_predict.py:85] load_model_config params: model_path:ResNet50_vd_model, use_gpu:True,            gpu_id:0, use_profile:False, thread_num:2, mem_optim:True, ir_optim:False,            use_trt:False, use_feed_fetch_ops:False
INFO 2020-12-01 16:02:35,946 [operator.py:1046] [imagenet|0] Succ init
INFO 2020-12-01 16:02:37,154 [pipeline_server.py:50] (log_id=0) inference request name: self.name:imagenet
INFO 2020-12-01 16:02:37,156 [operator.py:1285] RequestOp unpack one request. log_id:0, clientip:172.17.0.8             name:, method:
INFO 2020-12-01 16:02:37,156 [dag.py:368] (data_id=0 log_id=0) Succ Generate ID 
ERROR 2020-12-01 16:02:37,168 [operator.py:639] (data_id=0 log_id=0) [imagenet|0] Failed to preprocess: 'numpy.ndarray' object has no attribute 'strip'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/paddle_serving_server_gpu/pipeline/operator.py", line 622, in _run_preprocess
    parsed_data, data_id, logid_dict.get(data_id))
  File "resnet50_web_service.py", line 44, in preprocess
    img = self.seq(im)
  File "/usr/lib/python2.7/site-packages/paddle_serving_app/reader/image_reader.py", line 486, in __call__
    img = t(img)
  File "/usr/lib/python2.7/site-packages/paddle_serving_app/reader/image_reader.py", line 562, in __call__
    resp = urllib.urlopen(img_url)
  File "/usr/lib64/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib64/python2.7/urllib.py", line 180, in open
    fullurl = unwrap(toBytes(fullurl))
  File "/usr/lib64/python2.7/urllib.py", line 1059, in unwrap
    url = url.strip()
AttributeError: 'numpy.ndarray' object has no attribute 'strip'
ERROR 2020-12-01 16:02:37,172 [dag.py:409] (data_id=0 log_id=0) Failed to predict: (data_id=0 log_id=0) [imagenet|0] Failed to preprocess: 'numpy.ndarray' object has no attribute 'strip'
WARNING 2020-12-01 16:03:27,535 [pipeline_server.py:479] [CONF] build_dag_each_worker not set, use default: False
WARNING 2020-12-01 16:03:27,535 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 16:03:27,535 [pipeline_server.py:479] [CONF] channel_size not set, use default: 0
WARNING 2020-12-01 16:03:27,535 [pipeline_server.py:479] [CONF] use_profile not set, use default: False
WARNING 2020-12-01 16:03:27,535 [pipeline_server.py:479] [CONF] client_type not set, use default: brpc
WARNING 2020-12-01 16:03:27,535 [pipeline_server.py:479] [CONF] tracer not set, use default: {}
WARNING 2020-12-01 16:03:27,536 [pipeline_server.py:479] [CONF] interval_s not set, use default: -1
WARNING 2020-12-01 16:03:27,536 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 16:03:27,536 [pipeline_server.py:479] [CONF] concurrency not set, use default: 1
WARNING 2020-12-01 16:03:27,536 [pipeline_server.py:479] [CONF] batch_size not set, use default: 1
WARNING 2020-12-01 16:03:27,536 [pipeline_server.py:479] [CONF] timeout not set, use default: -1
WARNING 2020-12-01 16:03:27,536 [pipeline_server.py:479] [CONF] auto_batching_timeout not set, use default: -1
WARNING 2020-12-01 16:03:27,536 [pipeline_server.py:479] [CONF] ir_optim not set, use default: False
WARNING 2020-12-01 16:03:27,536 [pipeline_server.py:479] [CONF] mem_optim not set, use default: True
WARNING 2020-12-01 16:03:27,536 [pipeline_server.py:479] [CONF] workdir not set, use default: 
WARNING 2020-12-01 16:03:27,536 [pipeline_server.py:479] [CONF] thread_num not set, use default: 2
WARNING 2020-12-01 16:03:27,537 [operator.py:128] imagenet Because auto_batching_timeout <= 0 or batch_size == 1, set auto_batching_timeout to None.
INFO 2020-12-01 16:03:27,537 [operator.py:151] local_service_conf: {'mem_optim': True, 'workdir': '', 'model_config': 'ResNet50_vd_model', 'devices': '0', 'fetch_list': ['price'], 'client_type': 'local_predictor', 'thread_num': 2, 'concurrency': 2, 'ir_optim': False}
INFO 2020-12-01 16:03:27,537 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12000])
INFO 2020-12-01 16:03:27,537 [operator.py:229] imagenet 
	input_ops: @DAGExecutor,
	server_endpoints: None
	fetch_list: ['price']
	client_config: ResNet50_vd_model/serving_server_conf.prototxt
	concurrency: 1,
	timeout(s): -1,
	retry: 1,
	batch_size: 1,
	auto_batching_timeout(s): None
INFO 2020-12-01 16:03:27,537 [pipeline_server.py:204] ============= PIPELINE SERVER =============
INFO 2020-12-01 16:03:27,537 [pipeline_server.py:207] 
{
    "dag":{
        "retry":1,
        "channel_size":0,
        "use_profile":false,
        "is_thread_op":false,
        "client_type":"brpc",
        "tracer":{
            "interval_s":-1
        }
    },
    "rpc_port":9999,
    "worker_num":1,
    "http_port":18082,
    "build_dag_each_worker":false,
    "op":{
        "imagenet":{
            "local_service_conf":{
                "mem_optim":true,
                "workdir":"",
                "model_config":"ResNet50_vd_model",
                "devices":"0",
                "fetch_list":[
                    "price"
                ],
                "client_type":"local_predictor",
                "thread_num":2,
                "concurrency":2,
                "ir_optim":false
            },
            "retry":1,
            "concurrency":1,
            "batch_size":1,
            "timeout":-1,
            "auto_batching_timeout":-1
        }
    }
}
INFO 2020-12-01 16:03:27,538 [pipeline_server.py:212] -------------------------------------------
INFO 2020-12-01 16:03:27,538 [operator.py:252] Op(imagenet) use local rpc service at port: [12000]
INFO 2020-12-01 16:03:27,552 [dag.py:493] [DAG] Succ init
INFO 2020-12-01 16:03:27,553 [dag.py:651] ================= USED OP =================
INFO 2020-12-01 16:03:27,553 [dag.py:654] imagenet
INFO 2020-12-01 16:03:27,554 [dag.py:655] -------------------------------------------
INFO 2020-12-01 16:03:27,588 [dag.py:784] [DAG] Succ build DAG
INFO 2020-12-01 16:03:27,593 [dag.py:816] [DAG] start
INFO 2020-12-01 16:03:27,594 [dag.py:181] [DAG] set in channel succ, name [@DAGExecutor]
INFO 2020-12-01 16:03:27,596 [pipeline_server.py:46] [PipelineServicer] succ init
INFO 2020-12-01 16:03:27,605 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12001])
INFO 2020-12-01 16:03:27,606 [operator.py:1036] Init cuda env in process 0
INFO 2020-12-01 16:03:28,375 [local_predict.py:85] load_model_config params: model_path:ResNet50_vd_model, use_gpu:True,            gpu_id:0, use_profile:False, thread_num:2, mem_optim:True, ir_optim:False,            use_trt:False, use_feed_fetch_ops:False
INFO 2020-12-01 16:03:29,818 [pipeline_server.py:50] (log_id=0) inference request name: self.name:imagenet
INFO 2020-12-01 16:03:29,820 [operator.py:1285] RequestOp unpack one request. log_id:0, clientip:172.17.0.8             name:, method:
INFO 2020-12-01 16:03:29,820 [dag.py:368] (data_id=0 log_id=0) Succ Generate ID 
INFO 2020-12-01 16:03:29,950 [operator.py:1046] [imagenet|0] Succ init
ERROR 2020-12-01 16:03:29,961 [operator.py:639] (data_id=0 log_id=0) [imagenet|0] Failed to preprocess: 'numpy.ndarray' object has no attribute 'strip'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/paddle_serving_server_gpu/pipeline/operator.py", line 622, in _run_preprocess
    parsed_data, data_id, logid_dict.get(data_id))
  File "resnet50_web_service.py", line 45, in preprocess
    img = self.seq(im)
  File "/usr/lib/python2.7/site-packages/paddle_serving_app/reader/image_reader.py", line 486, in __call__
    img = t(img)
  File "/usr/lib/python2.7/site-packages/paddle_serving_app/reader/image_reader.py", line 562, in __call__
    resp = urllib.urlopen(img_url)
  File "/usr/lib64/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib64/python2.7/urllib.py", line 180, in open
    fullurl = unwrap(toBytes(fullurl))
  File "/usr/lib64/python2.7/urllib.py", line 1059, in unwrap
    url = url.strip()
AttributeError: 'numpy.ndarray' object has no attribute 'strip'
ERROR 2020-12-01 16:03:29,966 [dag.py:409] (data_id=0 log_id=0) Failed to predict: (data_id=0 log_id=0) [imagenet|0] Failed to preprocess: 'numpy.ndarray' object has no attribute 'strip'
WARNING 2020-12-01 16:04:03,863 [pipeline_server.py:479] [CONF] build_dag_each_worker not set, use default: False
WARNING 2020-12-01 16:04:03,863 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 16:04:03,863 [pipeline_server.py:479] [CONF] channel_size not set, use default: 0
WARNING 2020-12-01 16:04:03,863 [pipeline_server.py:479] [CONF] use_profile not set, use default: False
WARNING 2020-12-01 16:04:03,864 [pipeline_server.py:479] [CONF] client_type not set, use default: brpc
WARNING 2020-12-01 16:04:03,864 [pipeline_server.py:479] [CONF] tracer not set, use default: {}
WARNING 2020-12-01 16:04:03,864 [pipeline_server.py:479] [CONF] interval_s not set, use default: -1
WARNING 2020-12-01 16:04:03,864 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 16:04:03,864 [pipeline_server.py:479] [CONF] concurrency not set, use default: 1
WARNING 2020-12-01 16:04:03,864 [pipeline_server.py:479] [CONF] batch_size not set, use default: 1
WARNING 2020-12-01 16:04:03,864 [pipeline_server.py:479] [CONF] timeout not set, use default: -1
WARNING 2020-12-01 16:04:03,864 [pipeline_server.py:479] [CONF] auto_batching_timeout not set, use default: -1
WARNING 2020-12-01 16:04:03,864 [pipeline_server.py:479] [CONF] ir_optim not set, use default: False
WARNING 2020-12-01 16:04:03,864 [pipeline_server.py:479] [CONF] mem_optim not set, use default: True
WARNING 2020-12-01 16:04:03,864 [pipeline_server.py:479] [CONF] workdir not set, use default: 
WARNING 2020-12-01 16:04:03,865 [pipeline_server.py:479] [CONF] thread_num not set, use default: 2
WARNING 2020-12-01 16:04:03,865 [operator.py:128] imagenet Because auto_batching_timeout <= 0 or batch_size == 1, set auto_batching_timeout to None.
INFO 2020-12-01 16:04:03,865 [operator.py:151] local_service_conf: {'mem_optim': True, 'workdir': '', 'model_config': 'ResNet50_vd_model', 'devices': '0', 'fetch_list': ['price'], 'client_type': 'local_predictor', 'thread_num': 2, 'concurrency': 2, 'ir_optim': False}
INFO 2020-12-01 16:04:03,865 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12000])
INFO 2020-12-01 16:04:03,865 [operator.py:229] imagenet 
	input_ops: @DAGExecutor,
	server_endpoints: None
	fetch_list: ['price']
	client_config: ResNet50_vd_model/serving_server_conf.prototxt
	concurrency: 1,
	timeout(s): -1,
	retry: 1,
	batch_size: 1,
	auto_batching_timeout(s): None
INFO 2020-12-01 16:04:03,865 [pipeline_server.py:204] ============= PIPELINE SERVER =============
INFO 2020-12-01 16:04:03,866 [pipeline_server.py:207] 
{
    "dag":{
        "retry":1,
        "channel_size":0,
        "use_profile":false,
        "is_thread_op":false,
        "client_type":"brpc",
        "tracer":{
            "interval_s":-1
        }
    },
    "rpc_port":9999,
    "worker_num":1,
    "http_port":18082,
    "build_dag_each_worker":false,
    "op":{
        "imagenet":{
            "local_service_conf":{
                "mem_optim":true,
                "workdir":"",
                "model_config":"ResNet50_vd_model",
                "devices":"0",
                "fetch_list":[
                    "price"
                ],
                "client_type":"local_predictor",
                "thread_num":2,
                "concurrency":2,
                "ir_optim":false
            },
            "retry":1,
            "concurrency":1,
            "batch_size":1,
            "timeout":-1,
            "auto_batching_timeout":-1
        }
    }
}
INFO 2020-12-01 16:04:03,866 [pipeline_server.py:212] -------------------------------------------
INFO 2020-12-01 16:04:03,866 [operator.py:252] Op(imagenet) use local rpc service at port: [12000]
INFO 2020-12-01 16:04:03,881 [dag.py:493] [DAG] Succ init
INFO 2020-12-01 16:04:03,882 [dag.py:651] ================= USED OP =================
INFO 2020-12-01 16:04:03,882 [dag.py:654] imagenet
INFO 2020-12-01 16:04:03,882 [dag.py:655] -------------------------------------------
INFO 2020-12-01 16:04:03,917 [dag.py:784] [DAG] Succ build DAG
INFO 2020-12-01 16:04:03,922 [dag.py:816] [DAG] start
INFO 2020-12-01 16:04:03,923 [dag.py:181] [DAG] set in channel succ, name [@DAGExecutor]
INFO 2020-12-01 16:04:03,926 [pipeline_server.py:46] [PipelineServicer] succ init
INFO 2020-12-01 16:04:03,935 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12001])
INFO 2020-12-01 16:04:03,935 [operator.py:1036] Init cuda env in process 0
INFO 2020-12-01 16:04:04,719 [local_predict.py:85] load_model_config params: model_path:ResNet50_vd_model, use_gpu:True,            gpu_id:0, use_profile:False, thread_num:2, mem_optim:True, ir_optim:False,            use_trt:False, use_feed_fetch_ops:False
INFO 2020-12-01 16:04:06,250 [operator.py:1046] [imagenet|0] Succ init
INFO 2020-12-01 16:04:07,754 [pipeline_server.py:50] (log_id=0) inference request name: self.name:imagenet
INFO 2020-12-01 16:04:07,756 [operator.py:1285] RequestOp unpack one request. log_id:0, clientip:172.17.0.8             name:, method:
INFO 2020-12-01 16:04:07,757 [dag.py:368] (data_id=0 log_id=0) Succ Generate ID 
ERROR 2020-12-01 16:04:07,776 [operator.py:733] (data_id=0 log_id=0) [imagenet|0] Failed to process(batch: [0]): Fetch names should not be empty or out of saved fetch list.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/paddle_serving_server_gpu/pipeline/operator.py", line 728, in _run_process
    midped_batch = self.process(feed_batch, typical_logid)
  File "/usr/lib/python2.7/site-packages/paddle_serving_server_gpu/pipeline/operator.py", line 437, in process
    log_id=typical_logid)
  File "/usr/lib/python2.7/site-packages/paddle_serving_app/local_predict.py", line 172, in predict
    "Fetch names should not be empty or out of saved fetch list.")
ValueError: Fetch names should not be empty or out of saved fetch list.
ERROR 2020-12-01 16:04:07,779 [dag.py:409] (data_id=0 log_id=0) Failed to predict: (data_id=0 log_id=0) [imagenet|0] Failed to process(batch: [0]): Fetch names should not be empty or out of saved fetch list.
WARNING 2020-12-01 16:12:29,513 [pipeline_server.py:479] [CONF] build_dag_each_worker not set, use default: False
WARNING 2020-12-01 16:12:29,513 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 16:12:29,513 [pipeline_server.py:479] [CONF] channel_size not set, use default: 0
WARNING 2020-12-01 16:12:29,513 [pipeline_server.py:479] [CONF] use_profile not set, use default: False
WARNING 2020-12-01 16:12:29,514 [pipeline_server.py:479] [CONF] client_type not set, use default: brpc
WARNING 2020-12-01 16:12:29,514 [pipeline_server.py:479] [CONF] tracer not set, use default: {}
WARNING 2020-12-01 16:12:29,514 [pipeline_server.py:479] [CONF] interval_s not set, use default: -1
WARNING 2020-12-01 16:12:29,514 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 16:12:29,514 [pipeline_server.py:479] [CONF] concurrency not set, use default: 1
WARNING 2020-12-01 16:12:29,514 [pipeline_server.py:479] [CONF] batch_size not set, use default: 1
WARNING 2020-12-01 16:12:29,514 [pipeline_server.py:479] [CONF] timeout not set, use default: -1
WARNING 2020-12-01 16:12:29,514 [pipeline_server.py:479] [CONF] auto_batching_timeout not set, use default: -1
WARNING 2020-12-01 16:12:29,514 [pipeline_server.py:479] [CONF] ir_optim not set, use default: False
WARNING 2020-12-01 16:12:29,514 [pipeline_server.py:479] [CONF] mem_optim not set, use default: True
WARNING 2020-12-01 16:12:29,514 [pipeline_server.py:479] [CONF] workdir not set, use default: 
WARNING 2020-12-01 16:12:29,514 [pipeline_server.py:479] [CONF] thread_num not set, use default: 2
WARNING 2020-12-01 16:12:29,515 [operator.py:128] imagenet Because auto_batching_timeout <= 0 or batch_size == 1, set auto_batching_timeout to None.
INFO 2020-12-01 16:12:29,515 [operator.py:151] local_service_conf: {'mem_optim': True, 'workdir': '', 'model_config': 'ResNet50_vd_model', 'devices': '0', 'fetch_list': ['price'], 'client_type': 'local_predictor', 'thread_num': 2, 'concurrency': 2, 'ir_optim': False}
INFO 2020-12-01 16:12:29,515 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12000])
INFO 2020-12-01 16:12:29,515 [operator.py:229] imagenet 
	input_ops: @DAGExecutor,
	server_endpoints: None
	fetch_list: ['price']
	client_config: ResNet50_vd_model/serving_server_conf.prototxt
	concurrency: 1,
	timeout(s): -1,
	retry: 1,
	batch_size: 1,
	auto_batching_timeout(s): None
INFO 2020-12-01 16:12:29,515 [pipeline_server.py:204] ============= PIPELINE SERVER =============
INFO 2020-12-01 16:12:29,516 [pipeline_server.py:207] 
{
    "dag":{
        "retry":1,
        "channel_size":0,
        "use_profile":false,
        "is_thread_op":false,
        "client_type":"brpc",
        "tracer":{
            "interval_s":-1
        }
    },
    "rpc_port":9999,
    "worker_num":1,
    "http_port":18082,
    "build_dag_each_worker":false,
    "op":{
        "imagenet":{
            "local_service_conf":{
                "mem_optim":true,
                "workdir":"",
                "model_config":"ResNet50_vd_model",
                "devices":"0",
                "fetch_list":[
                    "price"
                ],
                "client_type":"local_predictor",
                "thread_num":2,
                "concurrency":2,
                "ir_optim":false
            },
            "retry":1,
            "concurrency":1,
            "batch_size":1,
            "timeout":-1,
            "auto_batching_timeout":-1
        }
    }
}
INFO 2020-12-01 16:12:29,516 [pipeline_server.py:212] -------------------------------------------
INFO 2020-12-01 16:12:29,516 [operator.py:252] Op(imagenet) use local rpc service at port: [12000]
INFO 2020-12-01 16:12:29,530 [dag.py:493] [DAG] Succ init
INFO 2020-12-01 16:12:29,531 [dag.py:651] ================= USED OP =================
INFO 2020-12-01 16:12:29,531 [dag.py:654] imagenet
INFO 2020-12-01 16:12:29,531 [dag.py:655] -------------------------------------------
INFO 2020-12-01 16:12:29,564 [dag.py:784] [DAG] Succ build DAG
INFO 2020-12-01 16:12:29,568 [dag.py:816] [DAG] start
INFO 2020-12-01 16:12:29,569 [dag.py:181] [DAG] set in channel succ, name [@DAGExecutor]
INFO 2020-12-01 16:12:29,571 [pipeline_server.py:46] [PipelineServicer] succ init
INFO 2020-12-01 16:12:29,581 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12001])
INFO 2020-12-01 16:12:29,581 [operator.py:1036] Init cuda env in process 0
INFO 2020-12-01 16:12:30,390 [local_predict.py:85] load_model_config params: model_path:ResNet50_vd_model, use_gpu:True,            gpu_id:0, use_profile:False, thread_num:2, mem_optim:True, ir_optim:False,            use_trt:False, use_feed_fetch_ops:False
INFO 2020-12-01 16:12:31,908 [operator.py:1046] [imagenet|0] Succ init
INFO 2020-12-01 16:12:34,288 [pipeline_server.py:50] (log_id=0) inference request name: self.name:imagenet
INFO 2020-12-01 16:12:34,290 [operator.py:1285] RequestOp unpack one request. log_id:0, clientip:172.17.0.8             name:, method:
INFO 2020-12-01 16:12:34,290 [dag.py:368] (data_id=0 log_id=0) Succ Generate ID 
ERROR 2020-12-01 16:12:34,307 [operator.py:733] (data_id=0 log_id=0) [imagenet|0] Failed to process(batch: [0]): Fetch names should not be empty or out of saved fetch list.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/paddle_serving_server_gpu/pipeline/operator.py", line 728, in _run_process
    midped_batch = self.process(feed_batch, typical_logid)
  File "/usr/lib/python2.7/site-packages/paddle_serving_server_gpu/pipeline/operator.py", line 437, in process
    log_id=typical_logid)
  File "/usr/lib/python2.7/site-packages/paddle_serving_app/local_predict.py", line 172, in predict
    "Fetch names should not be empty or out of saved fetch list.")
ValueError: Fetch names should not be empty or out of saved fetch list.
ERROR 2020-12-01 16:12:34,310 [dag.py:409] (data_id=0 log_id=0) Failed to predict: (data_id=0 log_id=0) [imagenet|0] Failed to process(batch: [0]): Fetch names should not be empty or out of saved fetch list.
WARNING 2020-12-01 16:15:08,961 [pipeline_server.py:479] [CONF] build_dag_each_worker not set, use default: False
WARNING 2020-12-01 16:15:08,962 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 16:15:08,962 [pipeline_server.py:479] [CONF] channel_size not set, use default: 0
WARNING 2020-12-01 16:15:08,962 [pipeline_server.py:479] [CONF] use_profile not set, use default: False
WARNING 2020-12-01 16:15:08,962 [pipeline_server.py:479] [CONF] client_type not set, use default: brpc
WARNING 2020-12-01 16:15:08,962 [pipeline_server.py:479] [CONF] tracer not set, use default: {}
WARNING 2020-12-01 16:15:08,962 [pipeline_server.py:479] [CONF] interval_s not set, use default: -1
WARNING 2020-12-01 16:15:08,962 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 16:15:08,962 [pipeline_server.py:479] [CONF] concurrency not set, use default: 1
WARNING 2020-12-01 16:15:08,962 [pipeline_server.py:479] [CONF] batch_size not set, use default: 1
WARNING 2020-12-01 16:15:08,962 [pipeline_server.py:479] [CONF] timeout not set, use default: -1
WARNING 2020-12-01 16:15:08,962 [pipeline_server.py:479] [CONF] auto_batching_timeout not set, use default: -1
WARNING 2020-12-01 16:15:08,963 [pipeline_server.py:479] [CONF] ir_optim not set, use default: False
WARNING 2020-12-01 16:15:08,963 [pipeline_server.py:479] [CONF] mem_optim not set, use default: True
WARNING 2020-12-01 16:15:08,963 [pipeline_server.py:479] [CONF] workdir not set, use default: 
WARNING 2020-12-01 16:15:08,963 [pipeline_server.py:479] [CONF] thread_num not set, use default: 2
WARNING 2020-12-01 16:15:08,963 [operator.py:128] imagenet Because auto_batching_timeout <= 0 or batch_size == 1, set auto_batching_timeout to None.
INFO 2020-12-01 16:15:08,963 [operator.py:151] local_service_conf: {'mem_optim': True, 'workdir': '', 'model_config': 'ResNet50_vd_model', 'devices': '0', 'fetch_list': ['score'], 'client_type': 'local_predictor', 'thread_num': 2, 'concurrency': 2, 'ir_optim': False}
INFO 2020-12-01 16:15:08,964 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12000])
INFO 2020-12-01 16:15:08,964 [operator.py:229] imagenet 
	input_ops: @DAGExecutor,
	server_endpoints: None
	fetch_list: ['score']
	client_config: ResNet50_vd_model/serving_server_conf.prototxt
	concurrency: 1,
	timeout(s): -1,
	retry: 1,
	batch_size: 1,
	auto_batching_timeout(s): None
INFO 2020-12-01 16:15:08,964 [pipeline_server.py:204] ============= PIPELINE SERVER =============
INFO 2020-12-01 16:15:08,964 [pipeline_server.py:207] 
{
    "dag":{
        "retry":1,
        "channel_size":0,
        "use_profile":false,
        "is_thread_op":false,
        "client_type":"brpc",
        "tracer":{
            "interval_s":-1
        }
    },
    "rpc_port":9999,
    "worker_num":1,
    "http_port":18082,
    "build_dag_each_worker":false,
    "op":{
        "imagenet":{
            "local_service_conf":{
                "mem_optim":true,
                "workdir":"",
                "model_config":"ResNet50_vd_model",
                "devices":"0",
                "fetch_list":[
                    "score"
                ],
                "client_type":"local_predictor",
                "thread_num":2,
                "concurrency":2,
                "ir_optim":false
            },
            "retry":1,
            "concurrency":1,
            "batch_size":1,
            "timeout":-1,
            "auto_batching_timeout":-1
        }
    }
}
INFO 2020-12-01 16:15:08,964 [pipeline_server.py:212] -------------------------------------------
INFO 2020-12-01 16:15:08,964 [operator.py:252] Op(imagenet) use local rpc service at port: [12000]
INFO 2020-12-01 16:15:08,979 [dag.py:493] [DAG] Succ init
INFO 2020-12-01 16:15:08,980 [dag.py:651] ================= USED OP =================
INFO 2020-12-01 16:15:08,980 [dag.py:654] imagenet
INFO 2020-12-01 16:15:08,980 [dag.py:655] -------------------------------------------
INFO 2020-12-01 16:15:09,013 [dag.py:784] [DAG] Succ build DAG
INFO 2020-12-01 16:15:09,018 [dag.py:816] [DAG] start
INFO 2020-12-01 16:15:09,019 [dag.py:181] [DAG] set in channel succ, name [@DAGExecutor]
INFO 2020-12-01 16:15:09,021 [pipeline_server.py:46] [PipelineServicer] succ init
INFO 2020-12-01 16:15:09,031 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12001])
INFO 2020-12-01 16:15:09,031 [operator.py:1036] Init cuda env in process 0
INFO 2020-12-01 16:15:09,809 [local_predict.py:85] load_model_config params: model_path:ResNet50_vd_model, use_gpu:True,            gpu_id:0, use_profile:False, thread_num:2, mem_optim:True, ir_optim:False,            use_trt:False, use_feed_fetch_ops:False
INFO 2020-12-01 16:15:11,333 [operator.py:1046] [imagenet|0] Succ init
INFO 2020-12-01 16:15:12,994 [pipeline_server.py:50] (log_id=0) inference request name: self.name:imagenet
INFO 2020-12-01 16:15:12,996 [operator.py:1285] RequestOp unpack one request. log_id:0, clientip:172.17.0.8             name:, method:
INFO 2020-12-01 16:15:12,996 [dag.py:368] (data_id=0 log_id=0) Succ Generate ID 
ERROR 2020-12-01 16:15:14,846 [operator.py:733] (data_id=0 log_id=0) [imagenet|0] Failed to process(batch: [0]): In user code:

    File "/home/xulongteng/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2488, in append_op
    attrs=kwargs.get("attrs", None))

    File "/home/xulongteng/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)

    File "/home/xulongteng/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 2803, in conv2d
    "data_format": data_format,

    File "/home/xulongteng/github/models/PaddleCV/image_classification/models/resnet_vd.py", line 146, in conv_bn_layer
    bias_attr=False)

    File "/home/xulongteng/github/models/PaddleCV/image_classification/models/resnet_vd.py", line 67, in net
    name='conv1_1')

    File "infer.py", line 99, in infer
    out = model.net(input=image, class_dim=args.class_dim)

    File "infer.py", line 211, in main
    infer(args)

    File "infer.py", line 215, in <module>
    main()


    InvalidArgumentError: The input of Op(Conv) should be a 4-D or 5-D Tensor. But received: input's dimension is 3, input's shape is [3, 224, 224].
      [Hint: Expected in_dims.size() == 4 || in_dims.size() == 5 == true, but received in_dims.size() == 4 || in_dims.size() == 5:0 != true:1.] (at /paddle/paddle/fluid/operators/conv_op.cc:61)
      [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
      [operator < conv2d > error]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/paddle_serving_server_gpu/pipeline/operator.py", line 728, in _run_process
    midped_batch = self.process(feed_batch, typical_logid)
  File "/usr/lib/python2.7/site-packages/paddle_serving_server_gpu/pipeline/operator.py", line 437, in process
    log_id=typical_logid)
  File "/usr/lib/python2.7/site-packages/paddle_serving_app/local_predict.py", line 201, in predict
    self.predictor.zero_copy_run()
ValueError: In user code:

    File "/home/xulongteng/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2488, in append_op
    attrs=kwargs.get("attrs", None))

    File "/home/xulongteng/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)

    File "/home/xulongteng/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 2803, in conv2d
    "data_format": data_format,

    File "/home/xulongteng/github/models/PaddleCV/image_classification/models/resnet_vd.py", line 146, in conv_bn_layer
    bias_attr=False)

    File "/home/xulongteng/github/models/PaddleCV/image_classification/models/resnet_vd.py", line 67, in net
    name='conv1_1')

    File "infer.py", line 99, in infer
    out = model.net(input=image, class_dim=args.class_dim)

    File "infer.py", line 211, in main
    infer(args)

    File "infer.py", line 215, in <module>
    main()


    InvalidArgumentError: The input of Op(Conv) should be a 4-D or 5-D Tensor. But received: input's dimension is 3, input's shape is [3, 224, 224].
      [Hint: Expected in_dims.size() == 4 || in_dims.size() == 5 == true, but received in_dims.size() == 4 || in_dims.size() == 5:0 != true:1.] (at /paddle/paddle/fluid/operators/conv_op.cc:61)
      [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
      [operator < conv2d > error]
ERROR 2020-12-01 16:15:14,850 [dag.py:409] (data_id=0 log_id=0) Failed to predict: (data_id=0 log_id=0) [imagenet|0] Failed to process(batch: [0]): In user code:

    File "/home/xulongteng/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2488, in append_op
    attrs=kwargs.get("attrs", None))

    File "/home/xulongteng/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)

    File "/home/xulongteng/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 2803, in conv2d
    "data_format": data_format,

    File "/home/xulongteng/github/models/PaddleCV/image_classification/models/resnet_vd.py", line 146, in conv_bn_layer
    bias_attr=False)

    File "/home/xulongteng/github/models/PaddleCV/image_classification/models/resnet_vd.py", line 67, in net
    name='conv1_1')

    File "infer.py", line 99, in infer
    out = model.net(input=image, class_dim=args.class_dim)

    File "infer.py", line 211, in main
    infer(args)

    File "infer.py", line 215, in <module>
    main()


    InvalidArgumentError: The input of Op(Conv) should be a 4-D or 5-D Tensor. But received: input's dimension is 3, input's shape is [3, 224, 224].
      [Hint: Expected in_dims.size() == 4 || in_dims.size() == 5 == true, but received in_dims.size() == 4 || in_dims.size() == 5:0 != true:1.] (at /paddle/paddle/fluid/operators/conv_op.cc:61)
      [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
      [operator < conv2d > error]
WARNING 2020-12-01 16:15:47,171 [pipeline_server.py:479] [CONF] build_dag_each_worker not set, use default: False
WARNING 2020-12-01 16:15:47,172 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 16:15:47,172 [pipeline_server.py:479] [CONF] channel_size not set, use default: 0
WARNING 2020-12-01 16:15:47,172 [pipeline_server.py:479] [CONF] use_profile not set, use default: False
WARNING 2020-12-01 16:15:47,172 [pipeline_server.py:479] [CONF] client_type not set, use default: brpc
WARNING 2020-12-01 16:15:47,172 [pipeline_server.py:479] [CONF] tracer not set, use default: {}
WARNING 2020-12-01 16:15:47,172 [pipeline_server.py:479] [CONF] interval_s not set, use default: -1
WARNING 2020-12-01 16:15:47,172 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 16:15:47,172 [pipeline_server.py:479] [CONF] concurrency not set, use default: 1
WARNING 2020-12-01 16:15:47,172 [pipeline_server.py:479] [CONF] batch_size not set, use default: 1
WARNING 2020-12-01 16:15:47,172 [pipeline_server.py:479] [CONF] timeout not set, use default: -1
WARNING 2020-12-01 16:15:47,173 [pipeline_server.py:479] [CONF] auto_batching_timeout not set, use default: -1
WARNING 2020-12-01 16:15:47,173 [pipeline_server.py:479] [CONF] ir_optim not set, use default: False
WARNING 2020-12-01 16:15:47,173 [pipeline_server.py:479] [CONF] mem_optim not set, use default: True
WARNING 2020-12-01 16:15:47,173 [pipeline_server.py:479] [CONF] workdir not set, use default: 
WARNING 2020-12-01 16:15:47,173 [pipeline_server.py:479] [CONF] thread_num not set, use default: 2
WARNING 2020-12-01 16:15:47,173 [operator.py:128] imagenet Because auto_batching_timeout <= 0 or batch_size == 1, set auto_batching_timeout to None.
INFO 2020-12-01 16:15:47,173 [operator.py:151] local_service_conf: {'mem_optim': True, 'workdir': '', 'model_config': 'ResNet50_vd_model', 'devices': '0', 'fetch_list': ['score'], 'client_type': 'local_predictor', 'thread_num': 2, 'concurrency': 2, 'ir_optim': False}
INFO 2020-12-01 16:15:47,174 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12000])
INFO 2020-12-01 16:15:47,174 [operator.py:229] imagenet 
	input_ops: @DAGExecutor,
	server_endpoints: None
	fetch_list: ['score']
	client_config: ResNet50_vd_model/serving_server_conf.prototxt
	concurrency: 1,
	timeout(s): -1,
	retry: 1,
	batch_size: 1,
	auto_batching_timeout(s): None
INFO 2020-12-01 16:15:47,174 [pipeline_server.py:204] ============= PIPELINE SERVER =============
INFO 2020-12-01 16:15:47,174 [pipeline_server.py:207] 
{
    "dag":{
        "retry":1,
        "channel_size":0,
        "use_profile":false,
        "is_thread_op":false,
        "client_type":"brpc",
        "tracer":{
            "interval_s":-1
        }
    },
    "rpc_port":9999,
    "worker_num":1,
    "http_port":18082,
    "build_dag_each_worker":false,
    "op":{
        "imagenet":{
            "local_service_conf":{
                "mem_optim":true,
                "workdir":"",
                "model_config":"ResNet50_vd_model",
                "devices":"0",
                "fetch_list":[
                    "score"
                ],
                "client_type":"local_predictor",
                "thread_num":2,
                "concurrency":2,
                "ir_optim":false
            },
            "retry":1,
            "concurrency":1,
            "batch_size":1,
            "timeout":-1,
            "auto_batching_timeout":-1
        }
    }
}
INFO 2020-12-01 16:15:47,174 [pipeline_server.py:212] -------------------------------------------
INFO 2020-12-01 16:15:47,174 [operator.py:252] Op(imagenet) use local rpc service at port: [12000]
INFO 2020-12-01 16:15:47,189 [dag.py:493] [DAG] Succ init
INFO 2020-12-01 16:15:47,190 [dag.py:651] ================= USED OP =================
INFO 2020-12-01 16:15:47,190 [dag.py:654] imagenet
INFO 2020-12-01 16:15:47,191 [dag.py:655] -------------------------------------------
INFO 2020-12-01 16:15:47,223 [dag.py:784] [DAG] Succ build DAG
INFO 2020-12-01 16:15:47,228 [dag.py:816] [DAG] start
INFO 2020-12-01 16:15:47,229 [dag.py:181] [DAG] set in channel succ, name [@DAGExecutor]
INFO 2020-12-01 16:15:47,232 [pipeline_server.py:46] [PipelineServicer] succ init
INFO 2020-12-01 16:15:47,241 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12001])
INFO 2020-12-01 16:15:47,242 [operator.py:1036] Init cuda env in process 0
INFO 2020-12-01 16:15:48,026 [local_predict.py:85] load_model_config params: model_path:ResNet50_vd_model, use_gpu:True,            gpu_id:0, use_profile:False, thread_num:2, mem_optim:True, ir_optim:False,            use_trt:False, use_feed_fetch_ops:False
INFO 2020-12-01 16:15:49,569 [operator.py:1046] [imagenet|0] Succ init
INFO 2020-12-01 16:15:51,287 [pipeline_server.py:50] (log_id=0) inference request name: self.name:imagenet
INFO 2020-12-01 16:15:51,289 [operator.py:1285] RequestOp unpack one request. log_id:0, clientip:172.17.0.8             name:, method:
INFO 2020-12-01 16:15:51,289 [dag.py:368] (data_id=0 log_id=0) Succ Generate ID 
INFO 2020-12-01 16:15:53,142 [dag.py:404] (data_id=0 log_id=0) Succ predict
ERROR 2020-12-01 16:15:53,143 [dag.py:470] (logid=0) Failed to pack RPC response package: error_info
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/paddle_serving_server_gpu/pipeline/dag.py", line 465, in _pack_for_rpc_resp
    return self._pack_rpc_func(channeldata)
  File "/usr/lib/python2.7/site-packages/paddle_serving_server_gpu/pipeline/operator.py", line 1346, in pack_response_package
    channeldata.id, resp.error_info))
AttributeError: error_info
WARNING 2020-12-01 16:19:18,214 [pipeline_server.py:479] [CONF] build_dag_each_worker not set, use default: False
WARNING 2020-12-01 16:19:18,214 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 16:19:18,214 [pipeline_server.py:479] [CONF] channel_size not set, use default: 0
WARNING 2020-12-01 16:19:18,214 [pipeline_server.py:479] [CONF] use_profile not set, use default: False
WARNING 2020-12-01 16:19:18,214 [pipeline_server.py:479] [CONF] client_type not set, use default: brpc
WARNING 2020-12-01 16:19:18,215 [pipeline_server.py:479] [CONF] tracer not set, use default: {}
WARNING 2020-12-01 16:19:18,215 [pipeline_server.py:479] [CONF] interval_s not set, use default: -1
WARNING 2020-12-01 16:19:18,215 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 16:19:18,215 [pipeline_server.py:479] [CONF] concurrency not set, use default: 1
WARNING 2020-12-01 16:19:18,215 [pipeline_server.py:479] [CONF] batch_size not set, use default: 1
WARNING 2020-12-01 16:19:18,215 [pipeline_server.py:479] [CONF] timeout not set, use default: -1
WARNING 2020-12-01 16:19:18,215 [pipeline_server.py:479] [CONF] auto_batching_timeout not set, use default: -1
WARNING 2020-12-01 16:19:18,215 [pipeline_server.py:479] [CONF] ir_optim not set, use default: False
WARNING 2020-12-01 16:19:18,215 [pipeline_server.py:479] [CONF] mem_optim not set, use default: True
WARNING 2020-12-01 16:19:18,215 [pipeline_server.py:479] [CONF] workdir not set, use default: 
WARNING 2020-12-01 16:19:18,215 [pipeline_server.py:479] [CONF] thread_num not set, use default: 2
WARNING 2020-12-01 16:19:18,216 [operator.py:128] imagenet Because auto_batching_timeout <= 0 or batch_size == 1, set auto_batching_timeout to None.
INFO 2020-12-01 16:19:18,216 [operator.py:151] local_service_conf: {'mem_optim': True, 'workdir': '', 'model_config': 'ResNet50_vd_model', 'devices': '0', 'fetch_list': ['score'], 'client_type': 'local_predictor', 'thread_num': 2, 'concurrency': 2, 'ir_optim': False}
INFO 2020-12-01 16:19:18,216 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12000])
INFO 2020-12-01 16:19:18,216 [operator.py:229] imagenet 
	input_ops: @DAGExecutor,
	server_endpoints: None
	fetch_list: ['score']
	client_config: ResNet50_vd_model/serving_server_conf.prototxt
	concurrency: 1,
	timeout(s): -1,
	retry: 1,
	batch_size: 1,
	auto_batching_timeout(s): None
INFO 2020-12-01 16:19:18,216 [pipeline_server.py:204] ============= PIPELINE SERVER =============
INFO 2020-12-01 16:19:18,217 [pipeline_server.py:207] 
{
    "dag":{
        "retry":1,
        "channel_size":0,
        "use_profile":false,
        "is_thread_op":false,
        "client_type":"brpc",
        "tracer":{
            "interval_s":-1
        }
    },
    "rpc_port":9999,
    "worker_num":1,
    "http_port":18082,
    "build_dag_each_worker":false,
    "op":{
        "imagenet":{
            "local_service_conf":{
                "mem_optim":true,
                "workdir":"",
                "model_config":"ResNet50_vd_model",
                "devices":"0",
                "fetch_list":[
                    "score"
                ],
                "client_type":"local_predictor",
                "thread_num":2,
                "concurrency":2,
                "ir_optim":false
            },
            "retry":1,
            "concurrency":1,
            "batch_size":1,
            "timeout":-1,
            "auto_batching_timeout":-1
        }
    }
}
INFO 2020-12-01 16:19:18,217 [pipeline_server.py:212] -------------------------------------------
INFO 2020-12-01 16:19:18,217 [operator.py:252] Op(imagenet) use local rpc service at port: [12000]
INFO 2020-12-01 16:19:18,232 [dag.py:493] [DAG] Succ init
INFO 2020-12-01 16:19:18,233 [dag.py:651] ================= USED OP =================
INFO 2020-12-01 16:19:18,233 [dag.py:654] imagenet
INFO 2020-12-01 16:19:18,233 [dag.py:655] -------------------------------------------
INFO 2020-12-01 16:19:18,267 [dag.py:784] [DAG] Succ build DAG
INFO 2020-12-01 16:19:18,272 [dag.py:816] [DAG] start
INFO 2020-12-01 16:19:18,273 [dag.py:181] [DAG] set in channel succ, name [@DAGExecutor]
INFO 2020-12-01 16:19:18,276 [pipeline_server.py:46] [PipelineServicer] succ init
INFO 2020-12-01 16:19:18,286 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12001])
INFO 2020-12-01 16:19:18,286 [operator.py:1036] Init cuda env in process 0
INFO 2020-12-01 16:19:19,147 [local_predict.py:85] load_model_config params: model_path:ResNet50_vd_model, use_gpu:True,            gpu_id:0, use_profile:False, thread_num:2, mem_optim:True, ir_optim:False,            use_trt:False, use_feed_fetch_ops:False
INFO 2020-12-01 16:19:20,849 [operator.py:1046] [imagenet|0] Succ init
INFO 2020-12-01 16:19:23,553 [pipeline_server.py:50] (log_id=0) inference request name: self.name:imagenet
INFO 2020-12-01 16:19:23,555 [operator.py:1285] RequestOp unpack one request. log_id:0, clientip:172.17.0.8             name:, method:
INFO 2020-12-01 16:19:23,555 [dag.py:368] (data_id=0 log_id=0) Succ Generate ID 
INFO 2020-12-01 16:19:25,421 [dag.py:404] (data_id=0 log_id=0) Succ predict
ERROR 2020-12-01 16:19:25,421 [dag.py:470] (logid=0) Failed to pack RPC response package: error_info
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/paddle_serving_server_gpu/pipeline/dag.py", line 465, in _pack_for_rpc_resp
    return self._pack_rpc_func(channeldata)
  File "/usr/lib/python2.7/site-packages/paddle_serving_server_gpu/pipeline/operator.py", line 1346, in pack_response_package
    channeldata.id, resp.error_info))
AttributeError: error_info
WARNING 2020-12-01 16:20:03,562 [pipeline_server.py:479] [CONF] build_dag_each_worker not set, use default: False
WARNING 2020-12-01 16:20:03,562 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 16:20:03,562 [pipeline_server.py:479] [CONF] channel_size not set, use default: 0
WARNING 2020-12-01 16:20:03,562 [pipeline_server.py:479] [CONF] use_profile not set, use default: False
WARNING 2020-12-01 16:20:03,562 [pipeline_server.py:479] [CONF] client_type not set, use default: brpc
WARNING 2020-12-01 16:20:03,562 [pipeline_server.py:479] [CONF] tracer not set, use default: {}
WARNING 2020-12-01 16:20:03,562 [pipeline_server.py:479] [CONF] interval_s not set, use default: -1
WARNING 2020-12-01 16:20:03,563 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 16:20:03,563 [pipeline_server.py:479] [CONF] concurrency not set, use default: 1
WARNING 2020-12-01 16:20:03,563 [pipeline_server.py:479] [CONF] batch_size not set, use default: 1
WARNING 2020-12-01 16:20:03,563 [pipeline_server.py:479] [CONF] timeout not set, use default: -1
WARNING 2020-12-01 16:20:03,563 [pipeline_server.py:479] [CONF] auto_batching_timeout not set, use default: -1
WARNING 2020-12-01 16:20:03,563 [pipeline_server.py:479] [CONF] ir_optim not set, use default: False
WARNING 2020-12-01 16:20:03,563 [pipeline_server.py:479] [CONF] mem_optim not set, use default: True
WARNING 2020-12-01 16:20:03,563 [pipeline_server.py:479] [CONF] workdir not set, use default: 
WARNING 2020-12-01 16:20:03,563 [pipeline_server.py:479] [CONF] thread_num not set, use default: 2
WARNING 2020-12-01 16:20:03,564 [operator.py:128] imagenet Because auto_batching_timeout <= 0 or batch_size == 1, set auto_batching_timeout to None.
INFO 2020-12-01 16:20:03,564 [operator.py:151] local_service_conf: {'mem_optim': True, 'workdir': '', 'model_config': 'ResNet50_vd_model', 'devices': '0', 'fetch_list': ['score'], 'client_type': 'local_predictor', 'thread_num': 2, 'concurrency': 2, 'ir_optim': False}
INFO 2020-12-01 16:20:03,564 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12000])
INFO 2020-12-01 16:20:03,564 [operator.py:229] imagenet 
	input_ops: @DAGExecutor,
	server_endpoints: None
	fetch_list: ['score']
	client_config: ResNet50_vd_model/serving_server_conf.prototxt
	concurrency: 1,
	timeout(s): -1,
	retry: 1,
	batch_size: 1,
	auto_batching_timeout(s): None
INFO 2020-12-01 16:20:03,564 [pipeline_server.py:204] ============= PIPELINE SERVER =============
INFO 2020-12-01 16:20:03,564 [pipeline_server.py:207] 
{
    "dag":{
        "retry":1,
        "channel_size":0,
        "use_profile":false,
        "is_thread_op":false,
        "client_type":"brpc",
        "tracer":{
            "interval_s":-1
        }
    },
    "rpc_port":9999,
    "worker_num":1,
    "http_port":18082,
    "build_dag_each_worker":false,
    "op":{
        "imagenet":{
            "local_service_conf":{
                "mem_optim":true,
                "workdir":"",
                "model_config":"ResNet50_vd_model",
                "devices":"0",
                "fetch_list":[
                    "score"
                ],
                "client_type":"local_predictor",
                "thread_num":2,
                "concurrency":2,
                "ir_optim":false
            },
            "retry":1,
            "concurrency":1,
            "batch_size":1,
            "timeout":-1,
            "auto_batching_timeout":-1
        }
    }
}
INFO 2020-12-01 16:20:03,564 [pipeline_server.py:212] -------------------------------------------
INFO 2020-12-01 16:20:03,564 [operator.py:252] Op(imagenet) use local rpc service at port: [12000]
INFO 2020-12-01 16:20:03,579 [dag.py:493] [DAG] Succ init
INFO 2020-12-01 16:20:03,580 [dag.py:651] ================= USED OP =================
INFO 2020-12-01 16:20:03,580 [dag.py:654] imagenet
INFO 2020-12-01 16:20:03,581 [dag.py:655] -------------------------------------------
INFO 2020-12-01 16:20:03,614 [dag.py:784] [DAG] Succ build DAG
INFO 2020-12-01 16:20:03,618 [dag.py:816] [DAG] start
INFO 2020-12-01 16:20:03,619 [dag.py:181] [DAG] set in channel succ, name [@DAGExecutor]
INFO 2020-12-01 16:20:03,622 [pipeline_server.py:46] [PipelineServicer] succ init
INFO 2020-12-01 16:20:03,631 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12001])
INFO 2020-12-01 16:20:03,631 [operator.py:1036] Init cuda env in process 0
INFO 2020-12-01 16:20:04,446 [local_predict.py:85] load_model_config params: model_path:ResNet50_vd_model, use_gpu:True,            gpu_id:0, use_profile:False, thread_num:2, mem_optim:True, ir_optim:False,            use_trt:False, use_feed_fetch_ops:False
INFO 2020-12-01 16:20:06,060 [operator.py:1046] [imagenet|0] Succ init
INFO 2020-12-01 16:20:09,671 [pipeline_server.py:50] (log_id=0) inference request name: self.name:imagenet
INFO 2020-12-01 16:20:09,673 [operator.py:1285] RequestOp unpack one request. log_id:0, clientip:172.17.0.8             name:, method:
INFO 2020-12-01 16:20:09,673 [dag.py:368] (data_id=0 log_id=0) Succ Generate ID 
INFO 2020-12-01 16:20:11,521 [dag.py:404] (data_id=0 log_id=0) Succ predict
ERROR 2020-12-01 16:20:11,522 [dag.py:470] (logid=0) Failed to pack RPC response package: error_info
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/paddle_serving_server_gpu/pipeline/dag.py", line 465, in _pack_for_rpc_resp
    return self._pack_rpc_func(channeldata)
  File "/usr/lib/python2.7/site-packages/paddle_serving_server_gpu/pipeline/operator.py", line 1346, in pack_response_package
    channeldata.id, resp.error_info))
AttributeError: error_info
WARNING 2020-12-01 16:20:46,067 [pipeline_server.py:479] [CONF] build_dag_each_worker not set, use default: False
WARNING 2020-12-01 16:20:46,068 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 16:20:46,068 [pipeline_server.py:479] [CONF] channel_size not set, use default: 0
WARNING 2020-12-01 16:20:46,068 [pipeline_server.py:479] [CONF] use_profile not set, use default: False
WARNING 2020-12-01 16:20:46,068 [pipeline_server.py:479] [CONF] client_type not set, use default: brpc
WARNING 2020-12-01 16:20:46,068 [pipeline_server.py:479] [CONF] tracer not set, use default: {}
WARNING 2020-12-01 16:20:46,068 [pipeline_server.py:479] [CONF] interval_s not set, use default: -1
WARNING 2020-12-01 16:20:46,068 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 16:20:46,068 [pipeline_server.py:479] [CONF] concurrency not set, use default: 1
WARNING 2020-12-01 16:20:46,069 [pipeline_server.py:479] [CONF] batch_size not set, use default: 1
WARNING 2020-12-01 16:20:46,069 [pipeline_server.py:479] [CONF] timeout not set, use default: -1
WARNING 2020-12-01 16:20:46,069 [pipeline_server.py:479] [CONF] auto_batching_timeout not set, use default: -1
WARNING 2020-12-01 16:20:46,069 [pipeline_server.py:479] [CONF] ir_optim not set, use default: False
WARNING 2020-12-01 16:20:46,069 [pipeline_server.py:479] [CONF] mem_optim not set, use default: True
WARNING 2020-12-01 16:20:46,069 [pipeline_server.py:479] [CONF] workdir not set, use default: 
WARNING 2020-12-01 16:20:46,069 [pipeline_server.py:479] [CONF] thread_num not set, use default: 2
WARNING 2020-12-01 16:20:46,069 [operator.py:128] imagenet Because auto_batching_timeout <= 0 or batch_size == 1, set auto_batching_timeout to None.
INFO 2020-12-01 16:20:46,070 [operator.py:151] local_service_conf: {'mem_optim': True, 'workdir': '', 'model_config': 'ResNet50_vd_model', 'devices': '0', 'fetch_list': ['score'], 'client_type': 'local_predictor', 'thread_num': 2, 'concurrency': 2, 'ir_optim': False}
INFO 2020-12-01 16:20:46,070 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12000])
INFO 2020-12-01 16:20:46,070 [operator.py:229] imagenet 
	input_ops: @DAGExecutor,
	server_endpoints: None
	fetch_list: ['score']
	client_config: ResNet50_vd_model/serving_server_conf.prototxt
	concurrency: 1,
	timeout(s): -1,
	retry: 1,
	batch_size: 1,
	auto_batching_timeout(s): None
INFO 2020-12-01 16:20:46,070 [pipeline_server.py:204] ============= PIPELINE SERVER =============
INFO 2020-12-01 16:20:46,070 [pipeline_server.py:207] 
{
    "dag":{
        "retry":1,
        "channel_size":0,
        "use_profile":false,
        "is_thread_op":false,
        "client_type":"brpc",
        "tracer":{
            "interval_s":-1
        }
    },
    "rpc_port":9999,
    "worker_num":1,
    "http_port":18082,
    "build_dag_each_worker":false,
    "op":{
        "imagenet":{
            "local_service_conf":{
                "mem_optim":true,
                "workdir":"",
                "model_config":"ResNet50_vd_model",
                "devices":"0",
                "fetch_list":[
                    "score"
                ],
                "client_type":"local_predictor",
                "thread_num":2,
                "concurrency":2,
                "ir_optim":false
            },
            "retry":1,
            "concurrency":1,
            "batch_size":1,
            "timeout":-1,
            "auto_batching_timeout":-1
        }
    }
}
INFO 2020-12-01 16:20:46,070 [pipeline_server.py:212] -------------------------------------------
INFO 2020-12-01 16:20:46,070 [operator.py:252] Op(imagenet) use local rpc service at port: [12000]
INFO 2020-12-01 16:20:46,085 [dag.py:493] [DAG] Succ init
INFO 2020-12-01 16:20:46,087 [dag.py:651] ================= USED OP =================
INFO 2020-12-01 16:20:46,087 [dag.py:654] imagenet
INFO 2020-12-01 16:20:46,087 [dag.py:655] -------------------------------------------
INFO 2020-12-01 16:20:46,120 [dag.py:784] [DAG] Succ build DAG
INFO 2020-12-01 16:20:46,125 [dag.py:816] [DAG] start
INFO 2020-12-01 16:20:46,127 [dag.py:181] [DAG] set in channel succ, name [@DAGExecutor]
INFO 2020-12-01 16:20:46,129 [pipeline_server.py:46] [PipelineServicer] succ init
INFO 2020-12-01 16:20:46,138 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12001])
INFO 2020-12-01 16:20:46,139 [operator.py:1036] Init cuda env in process 0
INFO 2020-12-01 16:20:46,915 [local_predict.py:85] load_model_config params: model_path:ResNet50_vd_model, use_gpu:True,            gpu_id:0, use_profile:False, thread_num:2, mem_optim:True, ir_optim:False,            use_trt:False, use_feed_fetch_ops:False
INFO 2020-12-01 16:20:48,450 [operator.py:1046] [imagenet|0] Succ init
INFO 2020-12-01 16:20:50,319 [pipeline_server.py:50] (log_id=0) inference request name: self.name:imagenet
INFO 2020-12-01 16:20:50,321 [operator.py:1285] RequestOp unpack one request. log_id:0, clientip:172.17.0.8             name:, method:
INFO 2020-12-01 16:20:50,321 [dag.py:368] (data_id=0 log_id=0) Succ Generate ID 
INFO 2020-12-01 16:20:52,155 [dag.py:404] (data_id=0 log_id=0) Succ predict
ERROR 2020-12-01 16:20:52,155 [dag.py:470] (logid=0) Failed to pack RPC response package: error_info
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/paddle_serving_server_gpu/pipeline/dag.py", line 465, in _pack_for_rpc_resp
    return self._pack_rpc_func(channeldata)
  File "/usr/lib/python2.7/site-packages/paddle_serving_server_gpu/pipeline/operator.py", line 1346, in pack_response_package
    channeldata.id, resp.error_info))
AttributeError: error_info
WARNING 2020-12-01 16:21:40,004 [pipeline_server.py:479] [CONF] build_dag_each_worker not set, use default: False
WARNING 2020-12-01 16:21:40,005 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 16:21:40,005 [pipeline_server.py:479] [CONF] channel_size not set, use default: 0
WARNING 2020-12-01 16:21:40,005 [pipeline_server.py:479] [CONF] use_profile not set, use default: False
WARNING 2020-12-01 16:21:40,005 [pipeline_server.py:479] [CONF] client_type not set, use default: brpc
WARNING 2020-12-01 16:21:40,005 [pipeline_server.py:479] [CONF] tracer not set, use default: {}
WARNING 2020-12-01 16:21:40,005 [pipeline_server.py:479] [CONF] interval_s not set, use default: -1
WARNING 2020-12-01 16:21:40,005 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 16:21:40,005 [pipeline_server.py:479] [CONF] concurrency not set, use default: 1
WARNING 2020-12-01 16:21:40,005 [pipeline_server.py:479] [CONF] batch_size not set, use default: 1
WARNING 2020-12-01 16:21:40,005 [pipeline_server.py:479] [CONF] timeout not set, use default: -1
WARNING 2020-12-01 16:21:40,005 [pipeline_server.py:479] [CONF] auto_batching_timeout not set, use default: -1
WARNING 2020-12-01 16:21:40,006 [pipeline_server.py:479] [CONF] ir_optim not set, use default: False
WARNING 2020-12-01 16:21:40,006 [pipeline_server.py:479] [CONF] mem_optim not set, use default: True
WARNING 2020-12-01 16:21:40,006 [pipeline_server.py:479] [CONF] workdir not set, use default: 
WARNING 2020-12-01 16:21:40,006 [pipeline_server.py:479] [CONF] thread_num not set, use default: 2
WARNING 2020-12-01 16:21:40,006 [operator.py:128] imagenet Because auto_batching_timeout <= 0 or batch_size == 1, set auto_batching_timeout to None.
INFO 2020-12-01 16:21:40,006 [operator.py:151] local_service_conf: {'mem_optim': True, 'workdir': '', 'model_config': 'ResNet50_vd_model', 'devices': '0', 'fetch_list': ['score'], 'client_type': 'local_predictor', 'thread_num': 2, 'concurrency': 2, 'ir_optim': False}
INFO 2020-12-01 16:21:40,006 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12000])
INFO 2020-12-01 16:21:40,007 [operator.py:229] imagenet 
	input_ops: @DAGExecutor,
	server_endpoints: None
	fetch_list: ['score']
	client_config: ResNet50_vd_model/serving_server_conf.prototxt
	concurrency: 1,
	timeout(s): -1,
	retry: 1,
	batch_size: 1,
	auto_batching_timeout(s): None
INFO 2020-12-01 16:21:40,007 [pipeline_server.py:204] ============= PIPELINE SERVER =============
INFO 2020-12-01 16:21:40,007 [pipeline_server.py:207] 
{
    "dag":{
        "retry":1,
        "channel_size":0,
        "use_profile":false,
        "is_thread_op":false,
        "client_type":"brpc",
        "tracer":{
            "interval_s":-1
        }
    },
    "rpc_port":9999,
    "worker_num":1,
    "http_port":18082,
    "build_dag_each_worker":false,
    "op":{
        "imagenet":{
            "local_service_conf":{
                "mem_optim":true,
                "workdir":"",
                "model_config":"ResNet50_vd_model",
                "devices":"0",
                "fetch_list":[
                    "score"
                ],
                "client_type":"local_predictor",
                "thread_num":2,
                "concurrency":2,
                "ir_optim":false
            },
            "retry":1,
            "concurrency":1,
            "batch_size":1,
            "timeout":-1,
            "auto_batching_timeout":-1
        }
    }
}
INFO 2020-12-01 16:21:40,007 [pipeline_server.py:212] -------------------------------------------
INFO 2020-12-01 16:21:40,007 [operator.py:252] Op(imagenet) use local rpc service at port: [12000]
INFO 2020-12-01 16:21:40,022 [dag.py:493] [DAG] Succ init
INFO 2020-12-01 16:21:40,023 [dag.py:651] ================= USED OP =================
INFO 2020-12-01 16:21:40,023 [dag.py:654] imagenet
INFO 2020-12-01 16:21:40,023 [dag.py:655] -------------------------------------------
INFO 2020-12-01 16:21:40,058 [dag.py:784] [DAG] Succ build DAG
INFO 2020-12-01 16:21:40,063 [dag.py:816] [DAG] start
INFO 2020-12-01 16:21:40,064 [dag.py:181] [DAG] set in channel succ, name [@DAGExecutor]
INFO 2020-12-01 16:21:40,067 [pipeline_server.py:46] [PipelineServicer] succ init
INFO 2020-12-01 16:21:40,076 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12001])
INFO 2020-12-01 16:21:40,076 [operator.py:1036] Init cuda env in process 0
INFO 2020-12-01 16:21:40,888 [local_predict.py:85] load_model_config params: model_path:ResNet50_vd_model, use_gpu:True,            gpu_id:0, use_profile:False, thread_num:2, mem_optim:True, ir_optim:False,            use_trt:False, use_feed_fetch_ops:False
INFO 2020-12-01 16:21:42,429 [operator.py:1046] [imagenet|0] Succ init
INFO 2020-12-01 16:21:44,012 [pipeline_server.py:50] (log_id=0) inference request name: self.name:imagenet
INFO 2020-12-01 16:21:44,013 [operator.py:1285] RequestOp unpack one request. log_id:0, clientip:172.17.0.8             name:, method:
INFO 2020-12-01 16:21:44,014 [dag.py:368] (data_id=0 log_id=0) Succ Generate ID 
INFO 2020-12-01 16:21:45,848 [dag.py:404] (data_id=0 log_id=0) Succ predict
ERROR 2020-12-01 16:21:45,848 [dag.py:470] (logid=0) Failed to pack RPC response package: error_info
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/paddle_serving_server_gpu/pipeline/dag.py", line 465, in _pack_for_rpc_resp
    return self._pack_rpc_func(channeldata)
  File "/usr/lib/python2.7/site-packages/paddle_serving_server_gpu/pipeline/operator.py", line 1346, in pack_response_package
    channeldata.id, resp.error_info))
AttributeError: error_info
WARNING 2020-12-01 16:23:23,425 [pipeline_server.py:479] [CONF] build_dag_each_worker not set, use default: False
WARNING 2020-12-01 16:23:23,426 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 16:23:23,426 [pipeline_server.py:479] [CONF] channel_size not set, use default: 0
WARNING 2020-12-01 16:23:23,426 [pipeline_server.py:479] [CONF] use_profile not set, use default: False
WARNING 2020-12-01 16:23:23,426 [pipeline_server.py:479] [CONF] client_type not set, use default: brpc
WARNING 2020-12-01 16:23:23,426 [pipeline_server.py:479] [CONF] tracer not set, use default: {}
WARNING 2020-12-01 16:23:23,426 [pipeline_server.py:479] [CONF] interval_s not set, use default: -1
WARNING 2020-12-01 16:23:23,426 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 16:23:23,426 [pipeline_server.py:479] [CONF] concurrency not set, use default: 1
WARNING 2020-12-01 16:23:23,426 [pipeline_server.py:479] [CONF] batch_size not set, use default: 1
WARNING 2020-12-01 16:23:23,427 [pipeline_server.py:479] [CONF] timeout not set, use default: -1
WARNING 2020-12-01 16:23:23,427 [pipeline_server.py:479] [CONF] auto_batching_timeout not set, use default: -1
WARNING 2020-12-01 16:23:23,427 [pipeline_server.py:479] [CONF] ir_optim not set, use default: False
WARNING 2020-12-01 16:23:23,427 [pipeline_server.py:479] [CONF] mem_optim not set, use default: True
WARNING 2020-12-01 16:23:23,427 [pipeline_server.py:479] [CONF] workdir not set, use default: 
WARNING 2020-12-01 16:23:23,427 [pipeline_server.py:479] [CONF] thread_num not set, use default: 2
WARNING 2020-12-01 16:23:23,427 [operator.py:128] imagenet Because auto_batching_timeout <= 0 or batch_size == 1, set auto_batching_timeout to None.
INFO 2020-12-01 16:23:23,428 [operator.py:151] local_service_conf: {'mem_optim': True, 'workdir': '', 'model_config': 'ResNet50_vd_model', 'devices': '0', 'fetch_list': ['score'], 'client_type': 'local_predictor', 'thread_num': 2, 'concurrency': 2, 'ir_optim': False}
INFO 2020-12-01 16:23:23,428 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12000])
INFO 2020-12-01 16:23:23,428 [operator.py:229] imagenet 
	input_ops: @DAGExecutor,
	server_endpoints: None
	fetch_list: ['score']
	client_config: ResNet50_vd_model/serving_server_conf.prototxt
	concurrency: 1,
	timeout(s): -1,
	retry: 1,
	batch_size: 1,
	auto_batching_timeout(s): None
INFO 2020-12-01 16:23:23,428 [pipeline_server.py:204] ============= PIPELINE SERVER =============
INFO 2020-12-01 16:23:23,428 [pipeline_server.py:207] 
{
    "dag":{
        "retry":1,
        "channel_size":0,
        "use_profile":false,
        "is_thread_op":false,
        "client_type":"brpc",
        "tracer":{
            "interval_s":-1
        }
    },
    "rpc_port":9999,
    "worker_num":1,
    "http_port":18082,
    "build_dag_each_worker":false,
    "op":{
        "imagenet":{
            "local_service_conf":{
                "mem_optim":true,
                "workdir":"",
                "model_config":"ResNet50_vd_model",
                "devices":"0",
                "fetch_list":[
                    "score"
                ],
                "client_type":"local_predictor",
                "thread_num":2,
                "concurrency":2,
                "ir_optim":false
            },
            "retry":1,
            "concurrency":1,
            "batch_size":1,
            "timeout":-1,
            "auto_batching_timeout":-1
        }
    }
}
INFO 2020-12-01 16:23:23,428 [pipeline_server.py:212] -------------------------------------------
INFO 2020-12-01 16:23:23,428 [operator.py:252] Op(imagenet) use local rpc service at port: [12000]
INFO 2020-12-01 16:23:23,442 [dag.py:493] [DAG] Succ init
INFO 2020-12-01 16:23:23,443 [dag.py:651] ================= USED OP =================
INFO 2020-12-01 16:23:23,443 [dag.py:654] imagenet
INFO 2020-12-01 16:23:23,443 [dag.py:655] -------------------------------------------
INFO 2020-12-01 16:23:23,475 [dag.py:784] [DAG] Succ build DAG
INFO 2020-12-01 16:23:23,480 [dag.py:816] [DAG] start
INFO 2020-12-01 16:23:23,481 [dag.py:181] [DAG] set in channel succ, name [@DAGExecutor]
INFO 2020-12-01 16:23:23,483 [pipeline_server.py:46] [PipelineServicer] succ init
INFO 2020-12-01 16:23:23,492 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12001])
INFO 2020-12-01 16:23:23,493 [operator.py:1036] Init cuda env in process 0
INFO 2020-12-01 16:23:24,283 [local_predict.py:85] load_model_config params: model_path:ResNet50_vd_model, use_gpu:True,            gpu_id:0, use_profile:False, thread_num:2, mem_optim:True, ir_optim:False,            use_trt:False, use_feed_fetch_ops:False
INFO 2020-12-01 16:23:25,811 [operator.py:1046] [imagenet|0] Succ init
INFO 2020-12-01 16:23:33,805 [pipeline_server.py:50] (log_id=0) inference request name: self.name:imagenet
INFO 2020-12-01 16:23:33,807 [operator.py:1285] RequestOp unpack one request. log_id:0, clientip:172.17.0.8             name:, method:
INFO 2020-12-01 16:23:33,808 [dag.py:368] (data_id=0 log_id=0) Succ Generate ID 
INFO 2020-12-01 16:23:35,616 [dag.py:404] (data_id=0 log_id=0) Succ predict
ERROR 2020-12-01 16:23:35,616 [dag.py:470] (logid=0) Failed to pack RPC response package: error_info
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/paddle_serving_server_gpu/pipeline/dag.py", line 465, in _pack_for_rpc_resp
    return self._pack_rpc_func(channeldata)
  File "/usr/lib/python2.7/site-packages/paddle_serving_server_gpu/pipeline/operator.py", line 1346, in pack_response_package
    channeldata.id, resp.error_info))
AttributeError: error_info
WARNING 2020-12-01 16:24:04,157 [pipeline_server.py:479] [CONF] build_dag_each_worker not set, use default: False
WARNING 2020-12-01 16:24:04,157 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 16:24:04,158 [pipeline_server.py:479] [CONF] channel_size not set, use default: 0
WARNING 2020-12-01 16:24:04,158 [pipeline_server.py:479] [CONF] use_profile not set, use default: False
WARNING 2020-12-01 16:24:04,158 [pipeline_server.py:479] [CONF] client_type not set, use default: brpc
WARNING 2020-12-01 16:24:04,158 [pipeline_server.py:479] [CONF] tracer not set, use default: {}
WARNING 2020-12-01 16:24:04,158 [pipeline_server.py:479] [CONF] interval_s not set, use default: -1
WARNING 2020-12-01 16:24:04,158 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 16:24:04,158 [pipeline_server.py:479] [CONF] concurrency not set, use default: 1
WARNING 2020-12-01 16:24:04,158 [pipeline_server.py:479] [CONF] batch_size not set, use default: 1
WARNING 2020-12-01 16:24:04,158 [pipeline_server.py:479] [CONF] timeout not set, use default: -1
WARNING 2020-12-01 16:24:04,158 [pipeline_server.py:479] [CONF] auto_batching_timeout not set, use default: -1
WARNING 2020-12-01 16:24:04,158 [pipeline_server.py:479] [CONF] ir_optim not set, use default: False
WARNING 2020-12-01 16:24:04,159 [pipeline_server.py:479] [CONF] mem_optim not set, use default: True
WARNING 2020-12-01 16:24:04,159 [pipeline_server.py:479] [CONF] workdir not set, use default: 
WARNING 2020-12-01 16:24:04,159 [pipeline_server.py:479] [CONF] thread_num not set, use default: 2
WARNING 2020-12-01 16:24:04,159 [operator.py:128] imagenet Because auto_batching_timeout <= 0 or batch_size == 1, set auto_batching_timeout to None.
INFO 2020-12-01 16:24:04,160 [operator.py:151] local_service_conf: {'mem_optim': True, 'workdir': '', 'model_config': 'ResNet50_vd_model', 'devices': '0', 'fetch_list': ['score'], 'client_type': 'local_predictor', 'thread_num': 2, 'concurrency': 2, 'ir_optim': False}
INFO 2020-12-01 16:24:04,160 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12000])
INFO 2020-12-01 16:24:04,160 [operator.py:229] imagenet 
	input_ops: @DAGExecutor,
	server_endpoints: None
	fetch_list: ['score']
	client_config: ResNet50_vd_model/serving_server_conf.prototxt
	concurrency: 1,
	timeout(s): -1,
	retry: 1,
	batch_size: 1,
	auto_batching_timeout(s): None
INFO 2020-12-01 16:24:04,160 [pipeline_server.py:204] ============= PIPELINE SERVER =============
INFO 2020-12-01 16:24:04,160 [pipeline_server.py:207] 
{
    "dag":{
        "retry":1,
        "channel_size":0,
        "use_profile":false,
        "is_thread_op":false,
        "client_type":"brpc",
        "tracer":{
            "interval_s":-1
        }
    },
    "rpc_port":9999,
    "worker_num":1,
    "http_port":18082,
    "build_dag_each_worker":false,
    "op":{
        "imagenet":{
            "local_service_conf":{
                "mem_optim":true,
                "workdir":"",
                "model_config":"ResNet50_vd_model",
                "devices":"0",
                "fetch_list":[
                    "score"
                ],
                "client_type":"local_predictor",
                "thread_num":2,
                "concurrency":2,
                "ir_optim":false
            },
            "retry":1,
            "concurrency":1,
            "batch_size":1,
            "timeout":-1,
            "auto_batching_timeout":-1
        }
    }
}
INFO 2020-12-01 16:24:04,160 [pipeline_server.py:212] -------------------------------------------
INFO 2020-12-01 16:24:04,160 [operator.py:252] Op(imagenet) use local rpc service at port: [12000]
INFO 2020-12-01 16:24:04,175 [dag.py:493] [DAG] Succ init
INFO 2020-12-01 16:24:04,177 [dag.py:651] ================= USED OP =================
INFO 2020-12-01 16:24:04,177 [dag.py:654] imagenet
INFO 2020-12-01 16:24:04,177 [dag.py:655] -------------------------------------------
INFO 2020-12-01 16:24:04,211 [dag.py:784] [DAG] Succ build DAG
INFO 2020-12-01 16:24:04,216 [dag.py:816] [DAG] start
INFO 2020-12-01 16:24:04,217 [dag.py:181] [DAG] set in channel succ, name [@DAGExecutor]
INFO 2020-12-01 16:24:04,220 [pipeline_server.py:46] [PipelineServicer] succ init
INFO 2020-12-01 16:24:04,229 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12001])
INFO 2020-12-01 16:24:04,230 [operator.py:1036] Init cuda env in process 0
INFO 2020-12-01 16:24:04,994 [local_predict.py:85] load_model_config params: model_path:ResNet50_vd_model, use_gpu:True,            gpu_id:0, use_profile:False, thread_num:2, mem_optim:True, ir_optim:False,            use_trt:False, use_feed_fetch_ops:False
INFO 2020-12-01 16:24:06,506 [operator.py:1046] [imagenet|0] Succ init
INFO 2020-12-01 16:24:08,530 [pipeline_server.py:50] (log_id=0) inference request name: self.name:imagenet
INFO 2020-12-01 16:24:08,531 [operator.py:1285] RequestOp unpack one request. log_id:0, clientip:172.17.0.8             name:, method:
INFO 2020-12-01 16:24:08,532 [dag.py:368] (data_id=0 log_id=0) Succ Generate ID 
INFO 2020-12-01 16:24:10,401 [dag.py:404] (data_id=0 log_id=0) Succ predict
ERROR 2020-12-01 16:24:10,402 [dag.py:470] (logid=0) Failed to pack RPC response package: error_info
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/paddle_serving_server_gpu/pipeline/dag.py", line 465, in _pack_for_rpc_resp
    return self._pack_rpc_func(channeldata)
  File "/usr/lib/python2.7/site-packages/paddle_serving_server_gpu/pipeline/operator.py", line 1346, in pack_response_package
    channeldata.id, resp.error_info))
AttributeError: error_info
WARNING 2020-12-01 16:25:12,508 [pipeline_server.py:479] [CONF] build_dag_each_worker not set, use default: False
WARNING 2020-12-01 16:25:12,508 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 16:25:12,508 [pipeline_server.py:479] [CONF] channel_size not set, use default: 0
WARNING 2020-12-01 16:25:12,508 [pipeline_server.py:479] [CONF] use_profile not set, use default: False
WARNING 2020-12-01 16:25:12,508 [pipeline_server.py:479] [CONF] client_type not set, use default: brpc
WARNING 2020-12-01 16:25:12,508 [pipeline_server.py:479] [CONF] tracer not set, use default: {}
WARNING 2020-12-01 16:25:12,509 [pipeline_server.py:479] [CONF] interval_s not set, use default: -1
WARNING 2020-12-01 16:25:12,509 [pipeline_server.py:479] [CONF] retry not set, use default: 1
WARNING 2020-12-01 16:25:12,509 [pipeline_server.py:479] [CONF] concurrency not set, use default: 1
WARNING 2020-12-01 16:25:12,509 [pipeline_server.py:479] [CONF] batch_size not set, use default: 1
WARNING 2020-12-01 16:25:12,509 [pipeline_server.py:479] [CONF] timeout not set, use default: -1
WARNING 2020-12-01 16:25:12,509 [pipeline_server.py:479] [CONF] auto_batching_timeout not set, use default: -1
WARNING 2020-12-01 16:25:12,509 [pipeline_server.py:479] [CONF] ir_optim not set, use default: False
WARNING 2020-12-01 16:25:12,509 [pipeline_server.py:479] [CONF] mem_optim not set, use default: True
WARNING 2020-12-01 16:25:12,509 [pipeline_server.py:479] [CONF] workdir not set, use default: 
WARNING 2020-12-01 16:25:12,509 [pipeline_server.py:479] [CONF] thread_num not set, use default: 2
WARNING 2020-12-01 16:25:12,510 [operator.py:128] imagenet Because auto_batching_timeout <= 0 or batch_size == 1, set auto_batching_timeout to None.
INFO 2020-12-01 16:25:12,510 [operator.py:151] local_service_conf: {'mem_optim': True, 'workdir': '', 'model_config': 'ResNet50_vd_model', 'devices': '0', 'fetch_list': ['score'], 'client_type': 'local_predictor', 'thread_num': 2, 'concurrency': 2, 'ir_optim': False}
INFO 2020-12-01 16:25:12,510 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12000])
INFO 2020-12-01 16:25:12,510 [operator.py:229] imagenet 
	input_ops: @DAGExecutor,
	server_endpoints: None
	fetch_list: ['score']
	client_config: ResNet50_vd_model/serving_server_conf.prototxt
	concurrency: 1,
	timeout(s): -1,
	retry: 1,
	batch_size: 1,
	auto_batching_timeout(s): None
INFO 2020-12-01 16:25:12,510 [pipeline_server.py:204] ============= PIPELINE SERVER =============
INFO 2020-12-01 16:25:12,510 [pipeline_server.py:207] 
{
    "dag":{
        "retry":1,
        "channel_size":0,
        "use_profile":false,
        "is_thread_op":false,
        "client_type":"brpc",
        "tracer":{
            "interval_s":-1
        }
    },
    "rpc_port":9999,
    "worker_num":1,
    "http_port":18082,
    "build_dag_each_worker":false,
    "op":{
        "imagenet":{
            "local_service_conf":{
                "mem_optim":true,
                "workdir":"",
                "model_config":"ResNet50_vd_model",
                "devices":"0",
                "fetch_list":[
                    "score"
                ],
                "client_type":"local_predictor",
                "thread_num":2,
                "concurrency":2,
                "ir_optim":false
            },
            "retry":1,
            "concurrency":1,
            "batch_size":1,
            "timeout":-1,
            "auto_batching_timeout":-1
        }
    }
}
INFO 2020-12-01 16:25:12,511 [pipeline_server.py:212] -------------------------------------------
INFO 2020-12-01 16:25:12,511 [operator.py:252] Op(imagenet) use local rpc service at port: [12000]
INFO 2020-12-01 16:25:12,525 [dag.py:493] [DAG] Succ init
INFO 2020-12-01 16:25:12,527 [dag.py:651] ================= USED OP =================
INFO 2020-12-01 16:25:12,527 [dag.py:654] imagenet
INFO 2020-12-01 16:25:12,527 [dag.py:655] -------------------------------------------
INFO 2020-12-01 16:25:12,563 [dag.py:784] [DAG] Succ build DAG
INFO 2020-12-01 16:25:12,568 [dag.py:816] [DAG] start
INFO 2020-12-01 16:25:12,569 [dag.py:181] [DAG] set in channel succ, name [@DAGExecutor]
INFO 2020-12-01 16:25:12,571 [pipeline_server.py:46] [PipelineServicer] succ init
INFO 2020-12-01 16:25:12,582 [local_service_handler.py:88] Model(ResNet50_vd_model) will be launch in gpu device: [0]. Port([12001])
INFO 2020-12-01 16:25:12,582 [operator.py:1036] Init cuda env in process 0
INFO 2020-12-01 16:25:13,360 [local_predict.py:86] load_model_config params: model_path:ResNet50_vd_model, use_gpu:True,            gpu_id:0, use_profile:False, thread_num:2, mem_optim:True, ir_optim:False,            use_trt:True, use_feed_fetch_ops:False
INFO 2020-12-01 16:25:14,920 [operator.py:1046] [imagenet|0] Succ init
INFO 2020-12-01 16:25:21,176 [pipeline_server.py:50] (log_id=0) inference request name: self.name:imagenet
INFO 2020-12-01 16:25:21,177 [operator.py:1285] RequestOp unpack one request. log_id:0, clientip:172.17.0.8             name:, method:
INFO 2020-12-01 16:25:21,178 [dag.py:368] (data_id=0 log_id=0) Succ Generate ID 
INFO 2020-12-01 16:25:23,002 [dag.py:404] (data_id=0 log_id=0) Succ predict
ERROR 2020-12-01 16:25:23,003 [dag.py:470] (logid=0) Failed to pack RPC response package: error_info
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/paddle_serving_server_gpu/pipeline/dag.py", line 465, in _pack_for_rpc_resp
    return self._pack_rpc_func(channeldata)
  File "/usr/lib/python2.7/site-packages/paddle_serving_server_gpu/pipeline/operator.py", line 1346, in pack_response_package
    channeldata.id, resp.error_info))
AttributeError: error_info
